(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],KM='០១២៣៤៥៦៧៨៩',AR='0123456789',MANIFEST='data/manifest.json',BOOKDIR='data/books/';
const FIREBASE={apiKey:'AIzaSyAu-2Vs76XXg2bxaIdbnnDGL6quvXyVuCg',authDomain:'bible1954.firebaseapp.com',databaseURL:'https://bible1954-default-rtdb.asia-southeast1.firebasedatabase.app',projectId:'bible1954',storageBucket:'bible1954.firebasestorage.app',messagingSenderId:'137475672629',appId:'1:137475672629:web:506b8264fa55a1052fbf7c',measurementId:'G-64K13FX89Y'};
const ADMIN_EMAIL='thythetopen@gmail.com',ROOT='bible1954';
let FONTS=[
 {id:'Krasar',name:'Krasar',css:'Krasar,"Noto Sans Khmer",sans-serif'},
 {id:'Kantumruy Pro',name:'Kantumruy Pro',css:'"Kantumruy Pro","Noto Sans Khmer",sans-serif'},
 {id:'Battambang',name:'Battambang',css:'Battambang,"Noto Sans Khmer",sans-serif'},
 {id:'Hanuman',name:'Hanuman',css:'Hanuman,"Noto Serif Khmer",serif'},
 {id:'Noto Sans Khmer',name:'Noto Sans Khmer',css:'"Noto Sans Khmer",sans-serif'},
 {id:'Noto Serif Khmer',name:'Noto Serif Khmer',css:'"Noto Serif Khmer",serif'},
 {id:'Siemreap',name:'Siemreap',css:'Siemreap,"Noto Sans Khmer",sans-serif'},
 {id:'Moul',name:'Moul',css:'Moul,"Noto Sans Khmer",sans-serif'}
];
async function loadExtraFonts(){try{const j=await fetch('assets/fonts/fonts.json',{cache:'no-store'}).then(r=>r.ok?r.json():null);for(const f of j?.fonts||[]){const family=f.family||f.id,url=`assets/fonts/${f.file}`;try{const ff=new FontFace(family,`url("${url}") format("${f.format||'truetype'}")`,{display:'swap'});document.fonts.add(ff);ff.load().catch(()=>{})}catch{}FONTS.push({id:f.id,name:f.name||f.id,css:`"${family}","Noto Sans Khmer",sans-serif`})}}catch(e){console.warn('fonts manifest',e)}const more=['Moulpali','Bayon','Dangrek','Content','Freehand','Khmer','Koulen','Metal','Odor Mean Chey','Preahvihear','Taprom'];for(const id of more)if(!FONTS.some(f=>f.id===id))FONTS.push({id,name:id,css:`"${id}","Noto Sans Khmer",sans-serif`});FONTS=[...new Map(FONTS.map(f=>[f.id,f])).values()]}
const E={loading:$('#loading'),reader:$('#reader'),hero:$('#chapterHero'),verses:$('#verseList'),strip:$('#chapterStrip'),mobileTitle:$('#mobileTitleMain'),desktopTitle:$('#desktopTitle'),sideBooks:$('#sideBooks'),rightBook:$('#rightBook'),rightChapters:$('#rightChapters'),picker:$('#pickerDlg'),pickerTitle:$('#pickerTitle'),pickerBack:$('#pickerBack'),pickerTabs:$('#pickerTabs'),bookGrid:$('#bookGrid'),chapterGrid:$('#chapterGrid'),search:$('#searchDlg'),searchInput:$('#searchInput'),searchMeta:$('#searchMeta'),results:$('#results'),saved:$('#savedDlg'),savedList:$('#savedList'),settings:$('#settingsDlg'),font:$('#fontRange'),fontLabel:$('#fontLabel'),line:$('#lineRange'),lineLabel:$('#lineLabel'),themeSeg:$('#themeSeg'),dataInfo:$('#dataInfo'),tools:$('#verseTools'),toast:$('#toast'),note:$('#noteDlg'),noteRef:$('#noteRef'),noteText:$('#noteText'),profile:$('#profileDlg'),cacheStatus:$('#cacheStatus'),cacheMeta:$('#cacheMeta'),cacheProgress:$('#cacheProgress'),syncTitle:$('#syncTitle'),syncMeta:$('#syncMeta'),syncPill:$('#syncPill'),offlinePill:$('#offlinePill'),fontGrid:$('#fontGrid'),fontName:$('#fontName'),gate:$('#accessGate'),power:$('#powerDlg')};
let manifest,books=[],byId={},bookCache=new Map(),current={book:'JHN',chapter:3,verse:null},selected=null,pickerBook=null,sideTest='OT',searchWorker=null,searchToken=0,touchX=0,touchY=0;
let stateKey='kb54.device',state=defaultState(),firebase=null,authUser=null,allowAnonymous=true,remoteUnsub=null,configUnsub=null,syncTimer=null,applyingRemote=false;
let powerSlides=[],powerIndex=0,presentIndex=0,presentBlack=false,bookAliases=[];
function defaultState(){return{bookmarks:{},highlights:{},notes:{},lastRead:null,history:[],settings:{fs:19,lh:1.9,theme:'light',font:'Krasar'},powerslide:{theme:'dark',font:'Krasar',ratio:'wide'},updatedAt:0}}
const loadJSON=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},saveJSON=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const toKm=v=>String(v).replace(/\d/g,d=>KM[d]),fromKm=v=>String(v).replace(/[០-៩]/g,d=>AR[KM.indexOf(d)]),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),key=(b,c,v)=>`${b}/${c}/${v}`;
const normalize=s=>fromKm(String(s||'')).normalize('NFKC').toLowerCase().replace(/[\s\u200b\u200c\u200d_]+/g,'').replace(/[–—]/g,'-');
const openDlg=d=>{if(!d.open)d.showModal()},closeDlg=d=>{if(d?.open)d.close()},toast=t=>{E.toast.textContent=t;E.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>E.toast.classList.remove('show'),1800)};
function hydrateState(raw){const d=defaultState(),x=raw&&typeof raw==='object'?raw:{};return{...d,...x,bookmarks:x.bookmarks||{},highlights:x.highlights||{},notes:x.notes||{},history:Array.isArray(x.history)?x.history:[],settings:{...d.settings,...(x.settings||{})},powerslide:{...d.powerslide,...(x.powerslide||{})},updatedAt:+x.updatedAt||0}}
function migrateLegacy(){let s=hydrateState(loadJSON(stateKey,null));if(!s.updatedAt){const b=loadJSON('kb54.bookmarks',null),h=loadJSON('kb54.highlights',null),n=loadJSON('kb54.notes',null),last=loadJSON('kb54.last',null);if(b||h||n||last){s.bookmarks=b||{};s.highlights=h||{};s.notes=n||{};s.lastRead=last||null;s.settings.fs=+localStorage.getItem('kb54.fs')||19;s.settings.lh=+localStorage.getItem('kb54.lh')||1.9;s.settings.theme=localStorage.getItem('kb54.theme')||'light';s.updatedAt=Date.now();saveJSON(stateKey,s)}}return s}
state=migrateLegacy();
function saveState(sync=true){state.updatedAt=Date.now();saveJSON(stateKey,state);applySettings();if(sync)scheduleSync()}
function useUserKey(uid){const k='kb54.user.'+uid;if(k===stateKey)return;const savedRaw=loadJSON(k,null),saved=savedRaw?hydrateState(savedRaw):null;if(saved&&saved.updatedAt>=state.updatedAt)state=saved;else saveJSON(k,state);stateKey=k;applySettings()}
function applySettings(){const s=state.settings;document.documentElement.style.setProperty('--fs',s.fs+'px');document.documentElement.style.setProperty('--lh',s.lh);document.documentElement.dataset.theme=s.theme;const f=FONTS.find(x=>x.id===s.font)||FONTS[0];document.documentElement.style.setProperty('--reader-font',f.css);if(E.font){E.font.value=s.fs;E.fontLabel.textContent=toKm(s.fs)+'px';E.line.value=s.lh;E.lineLabel.textContent=(+s.lh).toFixed(2);E.fontName.textContent=f.name;$$('[data-theme-btn]').forEach(x=>x.classList.toggle('active',x.dataset.themeBtn===s.theme));$$('.fontCard').forEach(x=>x.classList.toggle('active',x.dataset.font===s.font))}}
async function loadManifest(){const r=await fetch(MANIFEST);if(!r.ok)throw Error('manifest');return r.json()}
async function loadBook(id){if(bookCache.has(id))return bookCache.get(id);const r=await fetch(BOOKDIR+id+'.json');if(!r.ok)throw Error('book '+id);const b=await r.json();bookCache.set(id,b);return b}
function parseHash(){const m=location.hash.match(/^#([A-Z0-9]{3})\/(\d+)(?:\/(\d+))?$/);return m&&{book:m[1],chapter:+m[2],verse:m[3]?+m[3]:null}}
function updateHash(){const h=`#${current.book}/${current.chapter}${current.verse?'/'+current.verse:''}`;history.replaceState(null,'',h)}
function renderSide(){if(!books.length)return;$$('[data-side-test]').forEach(x=>x.classList.toggle('active',x.dataset.sideTest===sideTest));E.sideBooks.innerHTML=books.filter(b=>b.testament===sideTest).map(b=>`<button class="sideBook ${b.id===current.book?'current':''}" data-side-book="${b.id}"><span>${esc(b.nameKm)}</span><span>${toKm(b.chapterCount)}</span></button>`).join('')}
function renderChapters(){const b=byId[current.book];E.rightBook.textContent=b.nameKm;E.rightChapters.innerHTML=Array.from({length:b.chapterCount},(_,i)=>`<button class="rightCh ${i+1===current.chapter?'current':''}" data-right-ch="${i+1}">${toKm(i+1)}</button>`).join('');E.strip.innerHTML=Array.from({length:b.chapterCount},(_,i)=>`<button class="ch ${i+1===current.chapter?'active':''}" data-ch="${i+1}">${toKm(i+1)}</button>`).join('');requestAnimationFrame(()=>E.strip.querySelector('.active')?.scrollIntoView({inline:'center',block:'nearest'}))}
async function render(opts={}){const b=byId[current.book],data=await loadBook(current.book),ch=data.chapters[String(current.chapter)];if(!b||!ch)throw Error('Chapter not found');const title=`${b.nameKm} ${toKm(current.chapter)}`;E.mobileTitle.textContent=title;E.desktopTitle.innerHTML=`${esc(title)}<small>ព្រះគម្ពីរខ្មែរបកប្រែចាស់ ១៩៥៤</small>`;E.hero.innerHTML=`<h1>${esc(title)}</h1><p>${b.testament==='OT'?'ព្រះគម្ពីរសញ្ញាចាស់':'ព្រះគម្ពីរសញ្ញាថ្មី'}</p>`;E.verses.innerHTML=Object.entries(ch.verses).map(([v,t])=>{const k=key(b.id,current.chapter,v),hl=state.highlights[k]?` hl-${state.highlights[k]}`:'';return `<div class="verse${hl}${state.bookmarks[k]?' bookmarked':''}" data-v="${v}" id="v${v}"><div class="vn">${toKm(v)}</div><div class="vt">${esc(t)}</div></div>`}).join('');renderSide();renderChapters();selected=null;E.tools.classList.add('hidden');current.verse=opts.verse||current.verse||null;state.lastRead={book:current.book,chapter:current.chapter,verse:current.verse||null,scroll:0,updatedAt:Date.now()};const hist=`${current.book}/${current.chapter}`;state.history=[hist,...state.history.filter(x=>x!==hist)].slice(0,50);saveState();updateHash();if(current.verse){requestAnimationFrame(()=>{const el=$('#v'+current.verse);el?.scrollIntoView({block:'center'});el?.classList.add('selected');setTimeout(()=>el?.classList.remove('selected'),1600)})}else if(!opts.keepScroll)window.scrollTo(0,0)}
async function go(book,chapter,verse=null){if(!byId[book])return;current={book,chapter:Math.max(1,Math.min(+chapter,byId[book].chapterCount)),verse};sideTest=byId[book].testament;await render({verse})}
async function adjacent(d){let b=byId[current.book],ch=current.chapter+d;if(ch>=1&&ch<=b.chapterCount)return go(b.id,ch);const idx=books.findIndex(x=>x.id===b.id),next=books[idx+(d>0?1:-1)];if(next)go(next.id,d>0?1:next.chapterCount)}
function renderBooks(test='OT'){pickerBook=null;E.pickerBack.classList.add('hidden');E.pickerTitle.textContent='ជ្រើសរើសកណ្ឌ';E.pickerTabs.classList.remove('hidden');$$('#pickerTabs .tab').forEach(x=>x.classList.toggle('active',x.dataset.test===test));E.bookGrid.classList.remove('hidden');E.chapterGrid.classList.add('hidden');E.bookGrid.innerHTML=books.filter(b=>b.testament===test).map(b=>`<button class="bookBtn ${b.id===current.book?'current':''}" data-book="${b.id}"><strong>${esc(b.nameKm)}</strong><small>${toKm(b.chapterCount)} ជំពូក</small></button>`).join('')}
function showPicker(test=byId[current.book]?.testament||'OT'){renderBooks(test);openDlg(E.picker)}
function showChapters(id){pickerBook=byId[id];E.pickerBack.classList.remove('hidden');E.pickerTitle.textContent=pickerBook.nameKm;E.pickerTabs.classList.add('hidden');E.bookGrid.classList.add('hidden');E.chapterGrid.classList.remove('hidden');E.chapterGrid.innerHTML=Array.from({length:pickerBook.chapterCount},(_,i)=>`<button class="chapterBtn ${id===current.book&&i+1===current.chapter?'current':''}" data-ch="${i+1}">${toKm(i+1)}</button>`).join('')}
function buildAliases(){const a=new Map();const add=(name,id)=>{const n=normalize(name);if(n)a.set(n,id)};books.forEach(b=>{add(b.nameKm,b.id);const compact=b.nameKm.replace(/ទី\s*/g,'');add(compact,b.id);const n=normalize(compact),m=n.match(/^(.*?)([123])$/);if(m){add(m[2]+m[1],b.id);add(m[1]+'ទី'+m[2],b.id)}});const extra={
 'ហេព្រើ':'HEB','ហេប្រឺ':'HEB','អេភេសូរ':'EPH','អេភេសូ':'EPH','ភីលីព':'PHP','ភីលីពព':'PHP','រ៉ូម':'ROM','កិច្ចការ':'ACT','កិច្ចការរបស់ពួកសាវក':'ACT','យ៉ូហាន':'JHN','ម៉ាថាយ':'MAT','ម៉ាកុស':'MRK','លូកា':'LUK',
 '1កូរិនថូស':'1CO','កូរិនថូស1':'1CO','កូរិនថូសទី1':'1CO','2កូរិនថូស':'2CO','កូរិនថូស2':'2CO','កូរិនថូសទី2':'2CO',
 '1ពង្សាវតា':'1KI','1ពង្សាវតារក្សត្រ':'1KI','ពង្សាវតារក្សត្រ1':'1KI','2ពង្សាវតា':'2KI','2ពង្សាវតារក្សត្រ':'2KI','ពង្សាវតារក្សត្រ2':'2KI',
 '1របាក្សត្រ':'1CH','របាក្សត្រ1':'1CH','2របាក្សត្រ':'2CH','របាក្សត្រ2':'2CH',
 'ទំនុកតម្កើង':'PSA','ទំនុកដំកើង':'PSA','ទំនុកតំកើង':'PSA','ទំនុកតម្កើង':'PSA','ទំនុកដម្កើង':'PSA','ទំនុកសរសើរ':'PSA',
 '1សាំយូអែល':'1SA','1សាំយ៉ូអែល':'1SA','សាំយូអែល1':'1SA','សាំយ៉ូអែល1':'1SA','2សាំយូអែល':'2SA','2សាំយ៉ូអែល':'2SA','សាំយូអែល2':'2SA','សាំយ៉ូអែល2':'2SA',
 '1ពេត្រុស':'1PE','ពេត្រុស1':'1PE','2ពេត្រុស':'2PE','ពេត្រុស2':'2PE','1យ៉ូហាន':'1JN','យ៉ូហាន1':'1JN','2យ៉ូហាន':'2JN','យ៉ូហាន2':'2JN','3យ៉ូហាន':'3JN','យ៉ូហាន3':'3JN',
 '1ថែស្សាឡូនីច':'1TH','ថែស្សាឡូនីច1':'1TH','2ថែស្សាឡូនីច':'2TH','ថែស្សាឡូនីច2':'2TH','1ធីម៉ូថេ':'1TI','ធីម៉ូថេ1':'1TI','2ធីម៉ូថេ':'2TI','ធីម៉ូថេ2':'2TI',
 'ចោទិយកថា':'DEU','ទុតិយកថា':'DEU','ទុតិយកថា':'DEU','និក្ខមនំ':'EXO','និក្ខមន':'EXO'};Object.entries(extra).forEach(([n,id])=>add(n,id));bookAliases=[...a.entries()].sort((x,y)=>y[0].length-x[0].length)}
function editDistance(a,b){if(a===b)return 0;if(!a.length)return b.length;if(!b.length)return a.length;let prev=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){const cur=[i];for(let j=1;j<=b.length;j++)cur[j]=Math.min(cur[j-1]+1,prev[j]+1,prev[j-1]+(a[i-1]===b[j-1]?0:1));prev=cur}return prev[b.length]}
function resolveBookToken(token){const t=normalize(token);for(const [alias,id] of bookAliases)if(t===alias)return{id,match:'exact',alias};const lead=t.match(/^([123])(.*)$/),wantNum=lead?.[1]||null;let best=null,second=null;for(const [alias,id] of bookAliases){const aLead=alias.match(/^([123])(.*)$/);if(wantNum&&aLead?.[1]&&aLead[1]!==wantNum)continue;const d=editDistance(t,alias),limit=Math.max(1,Math.min(3,Math.floor(Math.max(t.length,alias.length)*.2)));if(d>limit)continue;const score=d/Math.max(t.length,alias.length);const item={id,alias,d,score};if(!best||score<best.score||(score===best.score&&d<best.d)){second=best;best=item}else if(!second||score<second.score)second=item}if(best&&(!second||best.id===second.id||second.score-best.score>=.035))return{id:best.id,match:'fuzzy',alias:best.alias,distance:best.d};return null}
function parseRef(q,requireVerse=false){let n=fromKm(String(q||'')).normalize('NFKC').toLowerCase().replace(/[\u200b\u200c\u200d]/g,'').replace(/[：]/g,':').replace(/[–—−]/g,'-').trim();n=n.replace(/^[•·▪◦*\-]+\s*/,'').replace(/[។៕;,]+\s*$/,'').replace(/\s+/g,'');for(const [alias,id] of bookAliases){if(!n.startsWith(alias))continue;const rest=n.slice(alias.length),m=rest.match(/^(\d+)(?::(\d+)(?:-(\d+))?)?$/);if(!m)continue;const chapter=+m[1],start=m[2]?+m[2]:null,end=m[3]?+m[3]:start;if(requireVerse&&!start)continue;if(chapter>=1&&chapter<=byId[id].chapterCount&&(!start||start>=1)&&(!end||end>=start))return{book:id,chapter,start,end,match:'exact',inputBook:alias,matchedAlias:alias}}const m=n.match(/^(.*?)(\d+)(?::(\d+)(?:-(\d+))?)?$/);if(!m)return null;const book=resolveBookToken(m[1]);if(!book)return null;const chapter=+m[2],start=m[3]?+m[3]:null,end=m[4]?+m[4]:start;if(requireVerse&&!start)return null;if(chapter<1||chapter>byId[book.id].chapterCount)return null;if(start&&start<1)return null;if(end&&end<start)return null;return{book:book.id,chapter,start,end,match:book.match,inputBook:m[1],matchedAlias:book.alias}}
function openSearch(){E.searchInput.value='';E.results.innerHTML='';E.searchMeta.textContent='ឧ. យ៉ូហាន 3:16 · សេចក្ដីស្រឡាញ់';openDlg(E.search);setTimeout(()=>E.searchInput.focus(),80)}
function ensureWorker(){if(searchWorker)return;searchWorker=new Worker('search-worker.js');searchWorker.onmessage=e=>{const m=e.data;if(m.token!==searchToken)return;if(m.type==='progress')E.searchMeta.textContent=`កំពុងស្វែងរក… ${toKm(m.done)} / ${toKm(m.total)} កណ្ឌ`;if(m.type==='results'){E.searchMeta.textContent=`រកឃើញ ${toKm(m.results.length)} លទ្ធផល${m.limited?' (បង្ហាញ ១០០)':''}`;E.results.innerHTML=m.results.length?m.results.map(r=>`<button class="result" data-go="${r.book}/${r.chapter}/${r.verse}"><div class="resultRef">${esc(byId[r.book].nameKm)} ${toKm(r.chapter)}:${toKm(r.verse)}</div><div class="resultText">${esc(r.text)}</div></button>`).join(''):'<div class="empty">រកមិនឃើញ</div>'}}}
function runSearch(){const q=E.searchInput.value.trim();searchToken++;if(!q){E.searchMeta.textContent='ឧ. យ៉ូហាន 3:16 · សេចក្ដីស្រឡាញ់';E.results.innerHTML='';return}const r=parseRef(q);if(r){E.searchMeta.textContent='លេខយោង';E.results.innerHTML=`<button class="result" data-go="${r.book}/${r.chapter}/${r.start||''}"><div class="resultRef">${esc(byId[r.book].nameKm)} ${toKm(r.chapter)}${r.start?':'+toKm(r.start):''}</div><div class="resultText">ចុចដើម្បីបើក</div></button>`;return}if(normalize(q).length<2){E.searchMeta.textContent='សូមសរសេរយ៉ាងហោចណាស់ ២ តួអក្សរ';return}ensureWorker();E.searchMeta.textContent='កំពុងចាប់ផ្ដើមស្វែងរក…';E.results.innerHTML='';searchWorker.postMessage({type:'search',q,token:searchToken,books})}
function selectVerse(el){if(String(getSelection()).trim())return;E.verses.querySelectorAll('.selected').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');selected=+el.dataset.v;E.tools.classList.remove('hidden')}
async function selectedData(){if(!selected)return null;const b=await loadBook(current.book),text=b.chapters[String(current.chapter)].verses[String(selected)],meta=byId[current.book];return{book:meta,v:selected,text,k:key(meta.id,current.chapter,selected),ref:`${meta.nameKm} ${current.chapter}:${selected}`}}
async function copyText(s){try{await navigator.clipboard.writeText(s)}catch{const t=document.createElement('textarea');t.value=s;document.body.append(t);t.select();document.execCommand('copy');t.remove()}}
function renderSaved(type='bookmarks'){$$('[data-saved]').forEach(x=>x.classList.toggle('active',x.dataset.saved===type));const src=type==='notes'?state.notes:state.bookmarks,keys=Object.keys(src);if(!keys.length){E.savedList.innerHTML=`<div class="empty">${type==='notes'?'មិនទាន់មានកំណត់ត្រា':'មិនទាន់មានខដែលបានរក្សាទុក'}</div>`;return}E.savedList.innerHTML=keys.slice().reverse().map(k=>{const[b,c,v]=k.split('/'),val=type==='notes'?state.notes[k]:'';return `<div class="savedItem"><button class="result" style="border:0;padding:0;background:transparent" data-go="${b}/${c}/${v}"><div class="savedRef">${esc(byId[b]?.nameKm||b)} ${toKm(c)}:${toKm(v)}</div>${val?`<div class="savedPreview">${esc(typeof val==='string'?val:val.text||'')}</div>`:''}</button><button class="miniBtn" data-remove="${type}|${k}">×</button></div>`}).join('')}
function updateDataInfo(){E.dataInfo.textContent=`Bundled 1954 · ៦៦ កណ្ឌ · ១,១៨៩ ជំពូក · ${Number(manifest?.version?.verseCount||31101).toLocaleString()} ខ · Static JSON + Offline Cache`}
function setTheme(v){state.settings.theme=v;saveState();applySettings()}function cycleTheme(){const a=['light','sepia','dark'],n=a[(a.indexOf(state.settings.theme)+1)%3];setTheme(n)}
function renderFonts(){E.fontGrid.innerHTML=FONTS.map(f=>`<button class="fontCard ${state.settings.font===f.id?'active':''}" data-font="${esc(f.id)}"><span class="fontName">${esc(f.name)}</span><span class="fontPreview" style="font-family:${f.css}">ព្រះបន្ទូលនៃព្រះអម្ចាស់</span></button>`).join('')}
/* Service worker + offline */
async function swMessage(type,data={}){if(!navigator.serviceWorker)return Promise.reject(Error('Service Worker មិនគាំទ្រ'));const reg=await navigator.serviceWorker.ready,target=navigator.serviceWorker.controller||reg.active;if(!target)throw Error('Service Worker មិនទាន់រួចរាល់');return new Promise((resolve,reject)=>{const ch=new MessageChannel(),timer=setTimeout(()=>reject(Error('Timeout')),600000);ch.port1.onmessage=e=>{if(e.data?.type==='PROGRESS'){updateCacheProgress(e.data);return}clearTimeout(timer);if(e.data?.ok===false)reject(Error(e.data.error||'Service Worker error'));else resolve(e.data)};target.postMessage({type,...data},[ch.port2])})}
function updateCacheProgress(m){if(m.total){E.cacheProgress.style.width=Math.round(m.done/m.total*100)+'%';E.cacheStatus.textContent=`កំពុងទាញយក ${toKm(m.done)} / ${toKm(m.total)} កណ្ឌ`}}
async function refreshCacheStatus(){E.offlinePill.textContent=navigator.onLine?'Online':'Offline';E.offlinePill.classList.toggle('good',navigator.onLine);try{const s=await swMessage('BIBLE_STATUS');const count=s.count||0;E.cacheStatus.textContent=count>=66?'✓ Bible ទាំងមូលរួចរាល់ Offline':`${toKm(count)} / ៦៦ កណ្ឌ បាន Cache`;E.cacheMeta.textContent=count>=66?'អាចអានគ្រប់កណ្ឌដោយគ្មាន Internet':'កណ្ឌដែលបានបើកនឹង Cache ស្វ័យប្រវត្តិ';E.cacheProgress.style.width=Math.round(count/66*100)+'%'}catch{E.cacheStatus.textContent='Service Worker មិនទាន់ដំណើរការ';E.cacheMeta.textContent='បើកតាម localhost ឬ HTTPS'}}
async function downloadAllBible(){if(!navigator.onLine&&!navigator.serviceWorker?.controller)return toast('ត្រូវការ Internet លើកដំបូង');$('#downloadBible').disabled=true;try{await swMessage('CACHE_ALL_BIBLE');toast('Bible ៦៦ កណ្ឌ រួចរាល់ Offline')}catch(e){toast('ទាញយកមិនទាន់រួច៖ '+e.message)}finally{$('#downloadBible').disabled=false;refreshCacheStatus()}}
async function clearBibleCache(){if(!confirm('លុបតែ Bible cache?\n\nFirebase, login, bookmarks, highlights, notes, last-read និង settings មិនត្រូវបានលុបទេ។'))return;try{await swMessage('CLEAR_BIBLE');bookCache.clear();toast('បានលុប Bible cache ប៉ុណ្ណោះ');refreshCacheStatus()}catch(e){toast(e.message)}}
/* Firebase */
async function initFirebase(){try{const [appM,authM,dbM]=await Promise.all([import('https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js'),import('https://www.gstatic.com/firebasejs/12.19.0/firebase-database.js')]);const app=appM.initializeApp(FIREBASE),auth=authM.getAuth(app),db=dbM.getDatabase(app);await authM.setPersistence(auth,authM.browserLocalPersistence);firebase={appM,authM,dbM,app,auth,db};configUnsub=dbM.onValue(dbM.ref(db,ROOT+'/config/allowAnonymous'),snap=>{allowAnonymous=snap.exists()?snap.val()===true:true;applyAccessGate();updateAdminUI()},()=>{allowAnonymous=true;applyAccessGate()});authM.onAuthStateChanged(auth,async user=>{authUser=user;if(user){useUserKey(user.uid);await syncRemoteState();listenRemoteState();}else if(allowAnonymous){try{await authM.signInAnonymously(auth)}catch(e){console.warn(e)}}updateProfileUI();applyAccessGate()});window.addEventListener('online',()=>{syncRemoteState();refreshCacheStatus()});window.addEventListener('offline',refreshCacheStatus);updateSyncUI()}catch(e){console.warn('Firebase unavailable',e);firebase=null;updateSyncUI();updateProfileUI();applyAccessGate();if(!initFirebase.retryBound){initFirebase.retryBound=true;window.addEventListener('online',()=>{if(!firebase)initFirebase()})}}}
function isAdmin(){return !!authUser?.email&&authUser.email.toLowerCase()===ADMIN_EMAIL}
function userRef(){return firebase?.dbM.ref(firebase.db,`${ROOT}/users/${authUser.uid}/state`)}
async function syncRemoteState(){if(!firebase||!authUser||!navigator.onLine)return updateSyncUI();try{const snap=await firebase.dbM.get(userRef()),remote=snap.exists()?hydrateState(snap.val()):null;if(remote&&remote.updatedAt>state.updatedAt){applyingRemote=true;state=remote;saveJSON(stateKey,state);applySettings();renderFonts();await render({keepScroll:true});applyingRemote=false}else if(!remote||state.updatedAt>remote.updatedAt){await firebase.dbM.set(userRef(),state)}updateSyncUI(true)}catch(e){console.warn('sync',e);updateSyncUI(false)}}
function listenRemoteState(){if(remoteUnsub){remoteUnsub();remoteUnsub=null}if(!firebase||!authUser)return;remoteUnsub=firebase.dbM.onValue(userRef(),snap=>{if(applyingRemote||!snap.exists())return;const r=hydrateState(snap.val());if(r.updatedAt>state.updatedAt){state=r;saveJSON(stateKey,state);applySettings();renderFonts();render({keepScroll:true}).catch(()=>{})}},()=>{})}
function scheduleSync(){if(applyingRemote||!firebase||!authUser)return;clearTimeout(syncTimer);syncTimer=setTimeout(()=>syncRemoteState(),450)}
function updateSyncUI(ok=null){if(!E.syncTitle)return;if(!firebase){E.syncTitle.textContent='Local mode';E.syncMeta.textContent='Firebase SDK មិនអាចភ្ជាប់។ Bible នៅតែអាចអានបាន។';E.syncPill.textContent='Local';E.syncPill.classList.remove('good');return}if(!authUser){E.syncTitle.textContent='កំពុងចូល Anonymous...';E.syncMeta.textContent='';E.syncPill.textContent='Connecting';return}E.syncTitle.textContent=authUser.isAnonymous?'Anonymous Firebase':'Google + Firebase';E.syncMeta.textContent=authUser.isAnonymous?'ទិន្នន័យ sync តាម Anonymous UID':'Bookmarks · Highlights · Notes · Last-read · Settings sync';E.syncPill.textContent=ok===false?'Pending':navigator.onLine?'Synced':'Offline';E.syncPill.classList.toggle('good',ok!==false&&navigator.onLine)}
async function googleLogin(){if(!firebase)return toast('Firebase មិនទាន់ភ្ជាប់');const {authM,auth}=firebase,provider=new authM.GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});try{if(auth.currentUser?.isAnonymous){try{await authM.linkWithPopup(auth.currentUser,provider)}catch(e){if(['auth/credential-already-in-use','auth/email-already-in-use','auth/provider-already-linked'].includes(e.code))await authM.signInWithPopup(auth,provider);else throw e}}else await authM.signInWithPopup(auth,provider);closeDlg(E.profile)}catch(e){toast('Google login មិនបាន');console.warn(e)}}
async function googleLogout(){if(!firebase)return;await firebase.authM.signOut(firebase.auth);authUser=null;stateKey='kb54.device';state=hydrateState(loadJSON(stateKey,defaultState()));updateProfileUI();if(allowAnonymous)firebase.authM.signInAnonymously(firebase.auth).catch(()=>{})}
function updateAvatar(el,user){el.innerHTML='';if(user?.photoURL){const img=new Image();img.src=user.photoURL;img.alt='';el.append(img)}else el.textContent=(user?.displayName||user?.email||'G').trim()[0]?.toUpperCase()||'G'}
function updateProfileUI(){const user=authUser;$$('[data-avatar]').forEach(x=>updateAvatar(x,user));$$('[data-status-dot]').forEach(x=>x.classList.toggle('online',!!firebase&&!!user&&navigator.onLine));updateAvatar($('#profileAvatar'),user);$('#profileName').textContent=user?.displayName||(user?.isAnonymous?'Anonymous':'Guest');$('#profileEmail').textContent=user?.email||(user?.isAnonymous?'Anonymous Firebase User':'Not connected');$('#profileState').textContent=user?.isAnonymous?'អ្នកអាចភ្ជាប់ Google ដើម្បីរក្សា UID និងទិន្នន័យនេះ':'Google account';$('#googleLogin').textContent=user?.isAnonymous?'ភ្ជាប់គណនី Google':'ប្ដូរគណនី Google';$('#logoutBtn').classList.toggle('hidden',!user||user.isAnonymous);$('#adminBox').classList.toggle('hidden',!isAdmin());updateAdminUI();updateSyncUI()}
function updateAdminUI(){if(!$('#anonymousToggle'))return;$('#anonymousToggle').checked=allowAnonymous;$('#anonymousState').textContent=allowAnonymous?'FREE: ON':'FREE: OFF'}
async function setAnonymousAccess(v){if(!firebase||!isAdmin())return;try{await firebase.dbM.set(firebase.dbM.ref(firebase.db,ROOT+'/config/allowAnonymous'),!!v);toast(v?'FREE: ON':'FREE: OFF')}catch(e){toast('មិនអាចរក្សាទុក Admin setting')}}
function applyAccessGate(){const blocked=!allowAnonymous&&(!authUser||authUser.isAnonymous);E.gate.style.display=blocked?'grid':'none'}
/* Powerslide */
const SAMPLE=`ព្រះបន្ទូលម៉ោង5:30\nរ៉ូម1:1-7\nកិច្ចការ22:3\nភីលីព3:5\n\nព្រះបន្ទូលម៉ោង9:30\nចំណងជើង: ចំរើនកំឡាំងនៃមនុស្សខាងក្នុង\n2កូរិនថូស4:16-18\nអេភេសូរ3:16\nហេព្រើ11:24-26\n2ពង្សាវតា23:25-26\nរ៉ូម8:18\n\nការសំរេចចិត្តអនុវត្តន៏តាមព្រះបន្ទូល\nឈប់សម្លឹងមើលបញ្ហាដោយភ្នែកសាច់ឈាម។\nលុតជង្គង់អធិស្ឋានសុំព្រះពង្រឹង «មនុស្សខាងក្នុង»\nផ្ញើជីវិតលើរបស់ដែលនៅអស់កល្បជានិច្ច។`;
function initPowerUI(){const opts=FONTS.map(f=>`<option value="${esc(f.id)}">${esc(f.name)}</option>`).join('');$('#powerFont').innerHTML=opts;$('#powerFont').value=state.powerslide.font;$('#powerTheme').value=state.powerslide.theme;$('#powerRatio').value=state.powerslide.ratio;$('#powerInput').value=localStorage.getItem('kb54.power.draft')||''}
function savePowerDeck(){localStorage.setItem('kb54.power.deck',JSON.stringify({slides:powerSlides,input:$('#powerInput').value,updatedAt:Date.now()}))}
function loadPowerDeck(){const d=loadJSON('kb54.power.deck',null);if(d?.slides&&Array.isArray(d.slides)){powerSlides=d.slides;powerIndex=0;if(!$('#powerInput').value&&d.input)$('#powerInput').value=d.input}}
function openPower(){initPowerUI();if(!powerSlides.length)loadPowerDeck();openDlg(E.power);if(powerSlides.length)renderPower()}
function savePowerPrefs(){state.powerslide={theme:$('#powerTheme').value,font:$('#powerFont').value,ratio:$('#powerRatio').value};saveState();localStorage.setItem('kb54.power.draft',$('#powerInput').value)}
async function scriptureSlides(ref){const data=await loadBook(ref.book),ch=data.chapters[String(ref.chapter)];if(!ch)return[];let start=ref.start||1,end=ref.end||Math.max(...Object.keys(ch.verses).map(Number));end=Math.min(end,Math.max(...Object.keys(ch.verses).map(Number)));const entries=[];for(let v=start;v<=end;v++)if(ch.verses[String(v)])entries.push([v,ch.verses[String(v)]]);const groups=[];let g=[],chars=0;for(const item of entries){const add=item[1].length+12;if(g.length&&(g.length>=3||chars+add>470)){groups.push(g);g=[];chars=0}g.push(item);chars+=add}if(g.length)groups.push(g);return groups.map(group=>{const a=group[0][0],z=group[group.length-1][0],r=`${byId[ref.book].nameKm} ${toKm(ref.chapter)}:${toKm(a)}${z!==a?'–'+toKm(z):''}`;return{type:'scripture',title:r,ref:r,body:group.map(([v,t])=>`${toKm(v)}  ${t}`).join('\n'),book:ref.book,chapter:ref.chapter,start:a,end:z}})}
async function generatePower(){savePowerPrefs();const raw=$('#powerInput').value.replace(/\r/g,''),blocks=raw.split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean),slides=[],warnings=[];for(const block of blocks){const lines=block.split('\n').map(x=>x.trim()).filter(Boolean);let text=[];const flush=()=>{if(!text.length)return;slides.push({type:'text',title:text.length>1?text[0]:'',body:(text.length>1?text.slice(1):text).map(x=>text.length>1?'• '+x:x).join('\n')});text=[]};for(const line of lines){const ref=parseRef(line,true);if(ref){flush();const ss=await scriptureSlides(ref);if(ss.length)slides.push(...ss);else warnings.push('រកមិនឃើញ៖ '+line);continue}if(/^ព្រះបន្ទូលម៉ោង/.test(line)){flush();slides.push({type:'section',title:line,body:''});continue}if(/^ចំណងជើង\s*[:：]/.test(line)){flush();slides.push({type:'title',title:line.replace(/^ចំណងជើង\s*[:：]\s*/,''),body:''});continue}if(/[០-៩0-9]+\s*[:：]/.test(line)&&line.length<50)warnings.push('មិនយល់លេខយោង៖ '+line);text.push(line)}flush()}powerSlides=slides;powerIndex=0;$('#powerWarnings').textContent=warnings.join(' · ');savePowerDeck();renderPower();toast(`បានបង្កើត ${toKm(slides.length)} slides`)}
function powerThemeClass(){return 'theme-'+($('#powerTheme').value||'dark')}
function slideHTML(s,present=false){const font=FONTS.find(f=>f.id===$('#powerFont').value)||FONTS[0],cls=(s.type==='title'||s.type==='section')?'center':'';if(present)return `<div class="presentSlide ${powerThemeClass()} ${cls}" style="font-family:${font.css}">${s.ref?`<div class="presentRef">${esc(s.ref)}</div>`:''}${s.title?`<div class="presentTitle">${esc(s.title)}</div>`:''}${s.body?`<div class="presentBody">${esc(s.body)}</div>`:''}<div class="presentCounter">${toKm(presentIndex+1)} / ${toKm(powerSlides.length)}</div><div class="presentHint">← → · B = Black · Esc</div></div>`;return `<div class="powerCanvas ${$('#powerRatio').value==='standard'?'ratio43':''}"><div class="powerSlideContent ${powerThemeClass()} ${cls}" style="font-family:${font.css}">${s.ref?`<div class="powerSlideRef">${esc(s.ref)}</div>`:''}${s.title?`<div class="powerSlideTitle">${esc(s.title)}</div>`:''}${s.body?`<div class="powerSlideBody">${esc(s.body)}</div>`:''}<div class="powerSlideFoot">Powerslide · Bible 1954</div></div></div>`}
function renderPower(){savePowerPrefs();const thumbs=$('#powerThumbs');if(!powerSlides.length){thumbs.innerHTML='';$('#powerPreview').innerHTML='<div class="powerEmpty">មិនទាន់មាន slide</div>';$('#powerInspector').classList.add('hidden');return}thumbs.innerHTML=powerSlides.map((s,i)=>`<button class="powerThumb ${i===powerIndex?'active':''}" data-power-index="${i}"><div class="t">${esc(s.ref||s.title||('Slide '+(i+1)))}</div><div class="b">${esc((s.body||'').slice(0,85))}</div><span class="n">${i+1}</span></button>`).join('');const s=powerSlides[powerIndex];$('#powerPreview').innerHTML=slideHTML(s);$('#powerInspector').classList.remove('hidden');$('#powerEditTitle').value=s.title||s.ref||'';$('#powerEditBody').value=s.body||'';requestAnimationFrame(()=>thumbs.querySelector('.active')?.scrollIntoView({block:'nearest',inline:'center'}))}
function updatePowerEdit(){if(!powerSlides.length)return;const s=powerSlides[powerIndex];if(s.type==='scripture'){s.ref=$('#powerEditTitle').value;s.title=s.ref}else s.title=$('#powerEditTitle').value;s.body=$('#powerEditBody').value;savePowerDeck();renderPower()}
function movePower(d){const n=powerIndex+d;if(n<0||n>=powerSlides.length)return;[powerSlides[powerIndex],powerSlides[n]]=[powerSlides[n],powerSlides[powerIndex]];powerIndex=n;savePowerDeck();renderPower()}
function showPresent(i=0){if(!powerSlides.length)return toast('Generate slides ជាមុន');presentIndex=Math.max(0,Math.min(i,powerSlides.length-1));presentBlack=false;$('#presentBlack').classList.add('hidden');$('#presentContent').innerHTML=slideHTML(powerSlides[presentIndex],true);$('#presentStage').style.display='block';document.documentElement.requestFullscreen?.().catch(()=>{})}
function stepPresent(d){presentIndex=Math.max(0,Math.min(presentIndex+d,powerSlides.length-1));$('#presentContent').innerHTML=slideHTML(powerSlides[presentIndex],true)}
function stopPresent(){if($('#presentStage').style.display==='none')return;$('#presentStage').style.display='none';document.exitFullscreen?.().catch(()=>{})}
function loadScript(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.head.append(s)})}
async function exportPptx(){if(!powerSlides.length)return toast('Generate slides ជាមុន');const btn=$('#powerExport'),old=btn.textContent;btn.disabled=true;btn.textContent='Preparing…';try{if(!window.PptxGenJS)await loadScript('https://cdn.jsdelivr.net/npm/pptxgenjs@4.0.1/dist/pptxgen.bundle.js');if(!window.PptxGenJS)throw Error('PPTX engine');const pptx=new PptxGenJS();pptx.layout=$('#powerRatio').value==='standard'?'LAYOUT_4X3':'LAYOUT_WIDE';pptx.author='Powerslide · Bible1954';pptx.subject='Khmer Bible presentation';pptx.title='Powerslide';pptx.company='Bible1954';const theme=$('#powerTheme').value,font=$('#powerFont').value,wide=$('#powerRatio').value!=='standard',W=wide?13.333:10,H=7.5;const colors={dark:['101722','F8FBF9','69DFA0'],green:['083B25','FFFFFF','8AF0B5'],light:['F4F8F5','17231C','087F43'],minimal:['111111','FFFFFF','70E0A5']}[theme]||['101722','F8FBF9','69DFA0'];for(const s of powerSlides){const sl=pptx.addSlide();sl.background={color:colors[0]};if(s.ref)sl.addText(s.ref,{x:.75,y:.55,w:W-1.5,h:.45,fontFace:font,fontSize:18,bold:true,color:colors[2],margin:0,breakLine:false});if(s.type==='title'||s.type==='section'){sl.addText(s.title||'',{x:.9,y:2.1,w:W-1.8,h:1.5,fontFace:font,fontSize:32,bold:true,color:colors[1],align:'center',valign:'mid',margin:0});if(s.body)sl.addText(s.body,{x:1.1,y:3.8,w:W-2.2,h:1.8,fontFace:font,fontSize:22,color:colors[1],align:'center',valign:'mid',margin:0,breakLine:false})}else{if(s.title&&!s.ref)sl.addText(s.title,{x:.8,y:.6,w:W-1.6,h:.65,fontFace:font,fontSize:23,bold:true,color:colors[2],margin:0});sl.addText(s.body||'',{x:.85,y:s.ref?1.35:1.4,w:W-1.7,h:H-2,fontFace:font,fontSize:(s.body||'').length>650?19:23,color:colors[1],margin:0.04,breakLine:false,valign:'mid',fit:'shrink'})}sl.addText('Powerslide · Bible 1954',{x:W-2.8,y:H-.35,w:2.4,h:.18,fontFace:'Arial',fontSize:6,color:'808080',align:'right',margin:0})}await pptx.writeFile({fileName:'Powerslide-Bible1954.pptx'});toast('PPTX រួចរាល់')}catch(e){console.error(e);alert('Export PPTX ត្រូវការ Internet លើកដំបូង ដើម្បី cache PPTX engine។ Present mode នៅតែដំណើរការ offline។')}finally{btn.disabled=false;btn.textContent=old}}
/* events */
E.verses.onclick=e=>{const v=e.target.closest('.verse');if(v)selectVerse(v)};E.reader.onclick=e=>{if(!e.target.closest('.verse')){selected=null;E.tools.classList.add('hidden');E.verses.querySelectorAll('.selected').forEach(x=>x.classList.remove('selected'))}};
['mobileBooks','mobileTitle','navBooks'].forEach(id=>$('#'+id).onclick=()=>showPicker());['navSearch','deskSearch'].forEach(id=>$('#'+id).onclick=openSearch);['navPower','deskPower'].forEach(id=>$('#'+id).onclick=()=>location.href='powerslide.html');['mobileProfile','deskProfile'].forEach(id=>$('#'+id).onclick=()=>{updateProfileUI();openDlg(E.profile)});$('#navSaved').onclick=()=>{renderSaved();openDlg(E.saved)};$('#navSettings').onclick=()=>{renderFonts();updateDataInfo();refreshCacheStatus();openDlg(E.settings)};$('#prevChapter').onclick=()=>adjacent(-1);$('#nextChapter').onclick=()=>adjacent(1);$('#desktopTitleBtn').onclick=()=>showPicker();
$$('[data-close]').forEach(x=>x.onclick=()=>closeDlg($('#'+x.dataset.close)));E.pickerTabs.onclick=e=>{const x=e.target.closest('[data-test]');if(x)renderBooks(x.dataset.test)};E.bookGrid.onclick=e=>{const x=e.target.closest('[data-book]');if(x)showChapters(x.dataset.book)};E.chapterGrid.onclick=e=>{const x=e.target.closest('[data-ch]');if(x){go(pickerBook.id,+x.dataset.ch);closeDlg(E.picker)}};E.pickerBack.onclick=()=>renderBooks(pickerBook?.testament||'OT');E.strip.onclick=e=>{const x=e.target.closest('[data-ch]');if(x)go(current.book,+x.dataset.ch)};
$$('[data-side-test]').forEach(x=>x.onclick=()=>{sideTest=x.dataset.sideTest;renderSide()});E.sideBooks.onclick=e=>{const x=e.target.closest('[data-side-book]');if(x)go(x.dataset.sideBook,1)};E.rightChapters.onclick=e=>{const x=e.target.closest('[data-right-ch]');if(x)go(current.book,+x.dataset.rightCh)};
let st;E.searchInput.oninput=()=>{clearTimeout(st);st=setTimeout(runSearch,260)};E.results.onclick=e=>{const x=e.target.closest('[data-go]');if(!x)return;const[b,c,v]=x.dataset.go.split('/');go(b,+c,v?+v:null);closeDlg(E.search)};
E.tools.onclick=async e=>{const a=e.target.closest('[data-action]')?.dataset.action,d=await selectedData();if(!a||!d)return;if(a==='copy'){await copyText(`${d.ref} — ${d.text}`);toast('បានចម្លង')}else if(a==='share'){const text=`${d.ref} — ${d.text}`,url=location.origin+location.pathname+`#${d.book.id}/${current.chapter}/${d.v}`;if(navigator.share)navigator.share({title:d.ref,text,url}).catch(()=>{});else{await copyText(text+'\n'+url);toast('បានចម្លងតំណ')}}else if(a==='bookmark'){if(state.bookmarks[d.k])delete state.bookmarks[d.k];else state.bookmarks[d.k]=Date.now();saveState();await render({keepScroll:true});toast(state.bookmarks[d.k]?'បានរក្សាទុក':'បានដកចេញ')}else if(a==='highlight'){const seq=['yellow','green','blue','pink',null],n=seq[(seq.indexOf(state.highlights[d.k]||null)+1)%seq.length];if(n)state.highlights[d.k]=n;else delete state.highlights[d.k];saveState();await render({keepScroll:true});toast(n?'បានប្ដូរពណ៌':'បានដកពណ៌')}else if(a==='note'){E.noteRef.textContent=d.ref;E.noteText.value=typeof state.notes[d.k]==='string'?state.notes[d.k]:(state.notes[d.k]?.text||'');E.note.dataset.k=d.k;openDlg(E.note)}};
E.saved.onclick=e=>{const tab=e.target.closest('[data-saved]');if(tab)return renderSaved(tab.dataset.saved);const goEl=e.target.closest('[data-go]');if(goEl){const[b,c,v]=goEl.dataset.go.split('/');go(b,+c,+v);closeDlg(E.saved)}const rm=e.target.closest('[data-remove]');if(rm){const[type,k]=rm.dataset.remove.split('|');if(type==='notes')delete state.notes[k];else delete state.bookmarks[k];saveState();renderSaved(type);render({keepScroll:true})}};
$('#saveNote').onclick=()=>{const k=E.note.dataset.k,v=E.noteText.value.trim();if(v)state.notes[k]=v;else delete state.notes[k];saveState();closeDlg(E.note);toast('បានរក្សាទុក')};$('#deleteNote').onclick=()=>{delete state.notes[E.note.dataset.k];saveState();E.noteText.value='';closeDlg(E.note);toast('បានលុប')};
E.font.oninput=()=>{state.settings.fs=+E.font.value;saveState()};E.line.oninput=()=>{state.settings.lh=+E.line.value;saveState()};E.themeSeg.onclick=e=>{const x=e.target.closest('[data-theme-btn]');if(x)setTheme(x.dataset.themeBtn)};E.fontGrid.onclick=e=>{const x=e.target.closest('[data-font]');if(x){state.settings.font=x.dataset.font;saveState();renderFonts()}};$('#quickMinus').onclick=()=>{state.settings.fs=Math.max(15,state.settings.fs-1);saveState()};$('#quickPlus').onclick=()=>{state.settings.fs=Math.min(30,state.settings.fs+1);saveState()};$('#quickTheme').onclick=cycleTheme;$('#downloadBible').onclick=downloadAllBible;$('#clearBibleCache').onclick=clearBibleCache;
$('#googleLogin').onclick=googleLogin;$('#gateGoogle').onclick=googleLogin;$('#logoutBtn').onclick=googleLogout;$('#anonymousToggle').onchange=e=>setAnonymousAccess(e.target.checked);
$('#powerClose').onclick=()=>closeDlg(E.power);$('#powerSample').onclick=()=>{$('#powerInput').value=SAMPLE;localStorage.setItem('kb54.power.draft',SAMPLE)};$('#powerGenerate').onclick=()=>generatePower().catch(e=>{console.error(e);toast('Generate មិនបាន')});$('#powerTheme').onchange=renderPower;$('#powerFont').onchange=renderPower;$('#powerRatio').onchange=renderPower;$('#powerThumbs').onclick=e=>{const x=e.target.closest('[data-power-index]');if(x){powerIndex=+x.dataset.powerIndex;renderPower()}};let editTimer;['powerEditTitle','powerEditBody'].forEach(id=>$('#'+id).oninput=()=>{clearTimeout(editTimer);editTimer=setTimeout(updatePowerEdit,250)});$('#powerUp').onclick=()=>movePower(-1);$('#powerDown').onclick=()=>movePower(1);$('#powerDuplicate').onclick=()=>{if(!powerSlides.length)return;powerSlides.splice(powerIndex+1,0,structuredClone(powerSlides[powerIndex]));powerIndex++;savePowerDeck();renderPower()};$('#powerDelete').onclick=()=>{if(!powerSlides.length)return;powerSlides.splice(powerIndex,1);powerIndex=Math.max(0,Math.min(powerIndex,powerSlides.length-1));savePowerDeck();renderPower()};$('#powerPresent').onclick=()=>showPresent(powerIndex);$('#powerExport').onclick=exportPptx;
$('#presentStage').onclick=e=>{if(e.target.id==='presentStage'||e.target.closest('.presentSlide'))stepPresent(1)};
window.addEventListener('keydown',e=>{if($('#presentStage').style.display==='block'){if(e.key==='ArrowRight'||e.key==='PageDown'||e.key===' ')stepPresent(1);else if(e.key==='ArrowLeft'||e.key==='PageUp')stepPresent(-1);else if(e.key==='Escape')stopPresent();else if(e.key.toLowerCase()==='b'){presentBlack=!presentBlack;$('#presentBlack').classList.toggle('hidden',!presentBlack)}e.preventDefault();return}if(e.target.matches('input,textarea,select'))return;if(e.key==='ArrowLeft')adjacent(-1);if(e.key==='ArrowRight')adjacent(1);if(e.key==='/'){e.preventDefault();openSearch()}});
E.reader.addEventListener('touchstart',e=>{if(e.touches.length===1){touchX=e.touches[0].clientX;touchY=e.touches[0].clientY}},{passive:true});E.reader.addEventListener('touchend',e=>{const t=e.changedTouches[0],dx=t.clientX-touchX,dy=t.clientY-touchY;if(Math.abs(dx)>75&&Math.abs(dx)>Math.abs(dy)*1.5)adjacent(dx<0?1:-1)},{passive:true});window.addEventListener('hashchange',()=>{const h=parseHash();if(h&&(h.book!==current.book||h.chapter!==current.chapter||h.verse!==current.verse))go(h.book,h.chapter,h.verse)});
async function init(){manifest=await loadManifest();books=manifest.books.sort((a,b)=>a.order-b.order);byId=Object.fromEntries(books.map(b=>[b.id,b]));buildAliases();await loadExtraFonts();renderFonts();const h=parseHash();if(h)current=h;else if(state.lastRead&&byId[state.lastRead.book])current={book:state.lastRead.book,chapter:state.lastRead.chapter,verse:null};applySettings();sideTest=byId[current.book].testament;await render();updateDataInfo();initPowerUI();E.loading.classList.add('hidden');if('serviceWorker'in navigator&&location.protocol!=='file:'){try{await navigator.serviceWorker.register('sw.js');await navigator.serviceWorker.ready}catch(e){console.warn(e)}}refreshCacheStatus();initFirebase();if(new URLSearchParams(location.search).get('tool')==='powerslide')location.href='powerslide.html'}
init().catch(e=>{console.error(e);E.loading.innerHTML=`<div class="empty"><strong>មិនអាចបើកព្រះគម្ពីរ</strong><br><br>${esc(e.message)}<br><br><small>សូមប្រើ RunServer.command / localhost មិនមែន file://</small></div>`});
})();
