(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],KM='០១២៣៤៥៦៧៨៩',AR='0123456789';
const FIREBASE={apiKey:'AIzaSyAu-2Vs76XXg2bxaIdbnnDGL6quvXyVuCg',authDomain:'bible1954.firebaseapp.com',databaseURL:'https://bible1954-default-rtdb.asia-southeast1.firebasedatabase.app',projectId:'bible1954',storageBucket:'bible1954.firebasestorage.app',messagingSenderId:'137475672629',appId:'1:137475672629:web:506b8264fa55a1052fbf7c'};
const ROOT='bible1954',MANIFEST='../../data/manifest.json',BOOKDIR='../../data/books/';
const BASE_FONTS=[
 ['Krasar','Krasar'],['Kantumruy Pro','Kantumruy Pro'],['Battambang','Battambang'],['Hanuman','Hanuman'],['Noto Sans Khmer','Noto Sans Khmer'],['Noto Serif Khmer','Noto Serif Khmer'],['Siemreap','Siemreap'],['Moul','Moul'],['Moulpali','Moulpali'],['Bayon','Bayon'],['Dangrek','Dangrek'],['Content','Content'],['Freehand','Freehand'],['Khmer','Khmer'],['Koulen','Koulen'],['Metal','Metal'],['Odor Mean Chey','Odor Mean Chey'],['Preahvihear','Preahvihear'],['Taprom','Taprom']
].map(([id,name])=>({id,name,family:id,css:`"${id}","Noto Sans Khmer",sans-serif`}));
const THEMES={
 'sunday-dark':{name:'Sunday Dark',bg:'#0b1110',fg:'#f8fbf9',accent:'#69dfa0'},
 'church-green':{name:'Church Green',bg:'#073820',fg:'#ffffff',accent:'#9af4bc'},
 'clean-light':{name:'Clean Light',bg:'#f7faf8',fg:'#17231c',accent:'#087f43'},
 'minimal-black':{name:'Minimal Black',bg:'#080808',fg:'#ffffff',accent:'#d9d9d9'}
};
const SAMPLE=`ព្រះបន្ទូលម៉ោង5:30
អេភេសូរ6:1-24
និក្ខមនំ20:12
ចោទិយកថា5:16
ម៉ាថាយ15:4
1ពេត្រុស1:13
1យ៉ូហាន4:4

ព្រះបន្ទូលម៉ោង9:30
ចំណងជើង: ផ្លូវឆ្ពោះទៅកាន់ជ័យជំនះពិតប្រាកដ
1សាំយ៉ូអែល7:5-12
1សាំយ៉ូអែល7:3-6
1សាំយ៉ូអែល7:7-11
1សាំយ៉ូអែល7:12-17
ទំនុកតំកើង48:14

ការសំរេចចិត្តអនុវត្តន៏តាមព្រះបន្ទូល
តើថ្ងៃនេះមានអ្វីខ្លះនៅក្នុងជីវិតរបស់អ្នកដែលត្រូវបោះបង់ចោល ដើម្បីថ្វាយកន្លែងជូន ព្រះវិញ? ចូរជឿជាក់លើព្រះអម្ចាស់ ព្រោះព្រះអង្គដែលបានជួយយើងកាលពីម្សិលមិញ ក៏នឹងជួយយើងនៅ ថ្ងៃនេះ និងថ្ងៃស្អែកផងដែរ។`;
let fonts=[...BASE_FONTS],manifest,books=[],byId={},aliases=[],bookCache=new Map();
let db,firebase,authUser,cloudUnsub,configUnsub,allowAnonymous=true,projects=[],project=null,slideId=null,elementId=null;
let historyStack=[],redoStack=[],saveTimer,cloudTimer,gridOn=false,presentIndex=0,presentBlack=false,presentTextScale=1,presentControlsTimer=null,presentFsStarted=false,drag=null,inlineEditId=null,libraryMonth='all',libraryProjectId=null,railWidth=Math.max(160,Math.min(430,Number(localStorage.getItem('powerslide.railWidth'))||220)),librarySidebarWidth=Math.max(180,Math.min(360,Number(localStorage.getItem('powerslide.librarySidebarWidth'))||228)),librarySidebarResize=null,railRenderRAF=0,lastElementTap={id:null,time:0};
let selectedSlideIds=new Set(),slideAnchorId=null,selectedElementIds=new Set(),selectionScope='canvas',savedTextRange=null,thumbDrag=null;

let projectSidebarHidden=localStorage.getItem("powerslide.projectSidebarHidden")==="1";
let editorSidebarHidden=localStorage.getItem("powerslide.editorSidebarHidden")==="1";
const uuid=()=>crypto.randomUUID?.()||('id-'+Date.now().toString(36)+Math.random().toString(36).slice(2));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toKm=v=>String(v).replace(/\d/g,d=>KM[d]),fromKm=v=>String(v).replace(/[០-៩]/g,d=>AR[KM.indexOf(d)]);
const norm=s=>fromKm(String(s||'')).normalize('NFKC').toLowerCase().replace(/[\s\u200b\u200c\u200d_]+/g,'').replace(/[–—]/g,'-');
const toast=t=>{const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1700)};
const clone=o=>JSON.parse(JSON.stringify(o));
let finderReqSeq=0,finderMirrorTimer=null;const finderPending=new Map();
function finderRequest(action,payload={}){if(window.parent===window)return Promise.resolve(null);const requestId=`psf_${Date.now().toString(36)}_${++finderReqSeq}`;return new Promise(resolve=>{const timer=setTimeout(()=>{finderPending.delete(requestId);resolve(null)},4000);finderPending.set(requestId,{resolve,timer});window.parent.postMessage({type:"tahoe-powerslide-finder",requestId,action,...payload},"*")})}
function mirrorProjectToFinder(p,delay=500){if(window.parent===window||!p)return;clearTimeout(finderMirrorTimer);const snap=clone(p);finderMirrorTimer=setTimeout(()=>finderRequest("upsert",{project:snap}),delay)}
function notifyTahoeProjectState(mode="editor"){if(window.parent===window)return;if(mode==="library"||!project){window.parent.postMessage({type:"tahoe-powerslide-state",title:"Powerslide Projects",subtitle:"Documents › Powerslide Projects"},"*");return}window.parent.postMessage({type:"tahoe-powerslide-state",title:project.title||"Untitled",subtitle:`${project.date||""}${project.service?" · "+project.service:""} · ${project.slides?.length||0} slides · Powerslide Projects`},"*")}
async function mergeFinderProjects(){if(window.parent===window)return;const data=await finderRequest("list");if(!data?.ok||!Array.isArray(data.projects))return;const by=new Map(projects.map(p=>[p.id,p]));for(const raw of data.projects){const fp=normalizeProject(raw),lp=by.get(fp.id);if(!lp||(+fp.updatedAt||0)>(+lp.updatedAt||0)){by.set(fp.id,fp);await idbPut(fp)}}projects=[...by.values()];for(const p of projects){const fp=data.projects.find(x=>x.id===p.id);if(!fp||(+p.updatedAt||0)>(+fp.updatedAt||0))mirrorProjectToFinder(p,100)}}

const hero=(path,cls='hi')=>`<svg class="${cls}" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.8" stroke="currentColor" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="${path}"/></svg>`;
const FILE_ICON=`<svg class="finderHeroFile" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M11 3.055A9.001 9.001 0 1020.945 13H11V3.055z"/><path stroke-linecap="round" stroke-linejoin="round" d="M20.488 9H15V3.512A9.025 9.025 0 0120.488 9z"/></svg>`;
function applyProjectSidebarWidth(){document.documentElement.style.setProperty('--ps-sidebar-w',librarySidebarWidth+'px')}

function applyProjectSidebarState(){
 const shell=$(".psProjectShell");
 shell?.classList.toggle("sidebar-hidden",projectSidebarHidden);
 document.documentElement.classList.toggle("ps-sidebar-hidden",projectSidebarHidden);
 ["#psSidebarToggleTop","#psSidebarToggleSide"].forEach(sel=>{
   const b=$(sel);if(!b)return;
   b.setAttribute("aria-expanded",String(!projectSidebarHidden));
   b.title=projectSidebarHidden?"Show sidebar":"Hide sidebar";
   const i=b.querySelector("i");if(i)i.className=projectSidebarHidden?"ri-layout-left-2-line":"ri-layout-left-line";
 });
}
function toggleProjectSidebar(){
 projectSidebarHidden=!projectSidebarHidden;
 localStorage.setItem("powerslide.projectSidebarHidden",projectSidebarHidden?"1":"0");
 applyProjectSidebarState()
}
function applyEditorSidebarState(){
 const ed=$("#editorView");
 ed?.classList.toggle("editor-sidebar-hidden",editorSidebarHidden);
 const b=$("#psEditorSidebarToggle");
 if(b){b.setAttribute("aria-expanded",String(!editorSidebarHidden));b.title=editorSidebarHidden?"Show slide sidebar":"Hide slide sidebar"}
}
function toggleEditorSidebar(){
 if(innerWidth<=900){$("#rail")?.classList.toggle("mobileOpen");return}
 editorSidebarHidden=!editorSidebarHidden;
 localStorage.setItem("powerslide.editorSidebarHidden",editorSidebarHidden?"1":"0");
 applyEditorSidebarState()
}
function bindProjectSidebarResize(){
 const h=$('#psProjectSplit');if(!h||h.dataset.bound)return;h.dataset.bound='1';
 const begin=e=>{
  if(innerWidth<=620)return;
  e.preventDefault();
  const x=e.touches?e.touches[0].clientX:e.clientX;
  librarySidebarResize={x,w:librarySidebarWidth};
  const move=ev=>{
   if(!librarySidebarResize)return;
   const cx=ev.touches?ev.touches[0].clientX:ev.clientX;
   librarySidebarWidth=Math.max(180,Math.min(360,Math.round(librarySidebarResize.w+(cx-librarySidebarResize.x))));
   localStorage.setItem('powerslide.librarySidebarWidth',librarySidebarWidth);
   applyProjectSidebarWidth()
  };
  const end=()=>{
   librarySidebarResize=null;
   removeEventListener('mousemove',move);removeEventListener('mouseup',end);
   removeEventListener('touchmove',move);removeEventListener('touchend',end)
  };
  addEventListener('mousemove',move);addEventListener('mouseup',end);
  addEventListener('touchmove',move,{passive:false});addEventListener('touchend',end)
 };
 h.addEventListener('mousedown',begin);
 h.addEventListener('touchstart',begin,{passive:false})
}

function applyLibrarySidebarWidth(){document.documentElement.style.setProperty('--finder-sidebar-w',librarySidebarWidth+'px')}
function bindLibrarySidebarResizer(){const h=$('#finderSidebarResizer');if(!h||h.dataset.bound)return;h.dataset.bound='1';const start=e=>{e.preventDefault();const x=e.touches?e.touches[0].clientX:e.clientX;librarySidebarResize={x,w:librarySidebarWidth};document.body.classList.add('col-resize');const move=ev=>{if(!librarySidebarResize)return;const cx=ev.touches?ev.touches[0].clientX:ev.clientX;librarySidebarWidth=Math.max(180,Math.min(360,Math.round(librarySidebarResize.w+(cx-librarySidebarResize.x))));localStorage.setItem('powerslide.librarySidebarWidth',librarySidebarWidth);applyLibrarySidebarWidth()};const end=()=>{librarySidebarResize=null;document.body.classList.remove('col-resize');window.removeEventListener('mousemove',move);window.removeEventListener('mouseup',end);window.removeEventListener('touchmove',move);window.removeEventListener('touchend',end)};window.addEventListener('mousemove',move);window.addEventListener('mouseup',end);window.addEventListener('touchmove',move,{passive:false});window.addEventListener('touchend',end)};h.addEventListener('mousedown',start);h.addEventListener('touchstart',start,{passive:false})}

function sanitizeRichHTML(html){const t=document.createElement('template');t.innerHTML=String(html||'');const allowed=new Set(['B','STRONG','I','EM','U','SPAN','FONT','DIV','BR','P','SUP','SUB']);const walk=n=>{for(const c of [...n.childNodes]){if(c.nodeType===1){if(!allowed.has(c.tagName)){c.replaceWith(...c.childNodes);continue}for(const a of [...c.attributes]){const k=a.name.toLowerCase();if(k.startsWith('on')||!['style','class','face','color'].includes(k))c.removeAttribute(a.name)}if(c.hasAttribute('style')){const keep=[];for(const d of c.style){if(['color','background-color','font-family','font-weight','font-style','text-decoration','text-align'].includes(d))keep.push(`${d}:${c.style.getPropertyValue(d)}`)}c.setAttribute('style',keep.join(';'))}walk(c)}}};walk(t.content);return t.innerHTML}
function plainFromRich(html){const d=document.createElement('div');d.innerHTML=String(html||'');return d.innerText.replace(/\u00a0/g,' ').replace(/\n{3,}/g,'\n\n').trimEnd()}
function selectedElements(){const s=currentSlide();if(!s)return[];const ids=selectedElementIds.size?selectedElementIds:new Set(elementId?[elementId]:[]);return s.elements.filter(e=>ids.has(e.id))}
function selectedTextElements(){return selectedElements().filter(isTextElement)}
function selectedSlides(){return project?.slides?.filter(s=>selectedSlideIds.has(s.id))||[]}
function setSelectionScope(scope){selectionScope=scope}

const openDlg=id=>{const d=typeof id==='string'?$('#'+id):id;if(d&&!d.open)d.showModal()};
const closeDlg=id=>{const d=typeof id==='string'?$('#'+id):id;if(d?.open)d.close()};
function nextSunday(){const d=new Date(),add=(7-d.getDay())%7;d.setDate(d.getDate()+add);return d.toISOString().slice(0,10)}
function monthLabel(date){try{return new Intl.DateTimeFormat('km-KH',{year:'numeric',month:'long'}).format(new Date(date+'T12:00:00'))}catch{return date.slice(0,7)}}
function dateLabel(date){try{return new Intl.DateTimeFormat('km-KH',{weekday:'short',day:'numeric',month:'short',year:'numeric'}).format(new Date(date+'T12:00:00'))}catch{return date}}
/* IndexedDB */
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open('Bible1954Powerslide',2);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('projects'))d.createObjectStore('projects',{keyPath:'id'})};r.onsuccess=()=>{db=r.result;res(db)};r.onerror=()=>rej(r.error)})}
function idbStore(mode='readonly'){return db.transaction('projects',mode).objectStore('projects')}
function idbAll(){return new Promise((res,rej)=>{const r=idbStore().getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
function idbPut(v){return new Promise((res,rej)=>{const r=idbStore('readwrite').put(v);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function idbDelete(id){return new Promise((res,rej)=>{const r=idbStore('readwrite').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
/* fonts */
async function loadFonts(){try{const j=await fetch('../../assets/fonts/fonts.json',{cache:'no-store'}).then(r=>r.ok?r.json():null);for(const f of j?.fonts||[]){const family=f.family||f.id,url=`../../assets/fonts/${f.file}`;try{const ff=new FontFace(family,`url("${url}") format("${f.format||'truetype'}")`,{display:'swap'});document.fonts.add(ff);ff.load().catch(()=>{})}catch{}fonts.push({id:f.id,name:f.name||f.id,family,css:`"${family}","Noto Sans Khmer",sans-serif`,local:true})}}catch(e){console.warn('local fonts',e)}fonts=[...new Map(fonts.map(f=>[f.id,f])).values()]}
function fontBy(id){return fonts.find(f=>f.id===id)||fonts[0]}
function fillFontSelect(sel,value){sel.innerHTML=fonts.map(f=>`<option value="${esc(f.id)}" ${f.id===value?'selected':''}>${esc(f.name)}</option>`).join('')}
/* Bible */
async function loadBible(){manifest=await fetch(MANIFEST).then(r=>r.json());books=[...manifest.books].sort((a,b)=>a.order-b.order);byId=Object.fromEntries(books.map(b=>[b.id,b]));buildAliases()}
async function loadBook(id){if(bookCache.has(id))return bookCache.get(id);const b=await fetch(BOOKDIR+id+'.json').then(r=>{if(!r.ok)throw Error(id);return r.json()});bookCache.set(id,b);return b}
function buildAliases(){const a=new Map();const add=(name,id)=>{const n=norm(name);if(n)a.set(n,id)};books.forEach(b=>{add(b.nameKm,b.id);const compact=b.nameKm.replace(/ទី\s*/g,'');add(compact,b.id);const n=norm(compact),m=n.match(/^(.*?)([123])$/);if(m){add(m[2]+m[1],b.id);add(m[1]+'ទី'+m[2],b.id)}});const extra={
 'ហេព្រើ':'HEB','ហេប្រឺ':'HEB','អេភេសូរ':'EPH','អេភេសូ':'EPH','ភីលីព':'PHP','ភីលីពព':'PHP','រ៉ូម':'ROM','កិច្ចការ':'ACT','កិច្ចការរបស់ពួកសាវក':'ACT','យ៉ូហាន':'JHN','ម៉ាថាយ':'MAT','ម៉ាកុស':'MRK','លូកា':'LUK',
 '1កូរិនថូស':'1CO','កូរិនថូស1':'1CO','កូរិនថូសទី1':'1CO','2កូរិនថូស':'2CO','កូរិនថូស2':'2CO','កូរិនថូសទី2':'2CO',
 '1ពង្សាវតា':'1KI','1ពង្សាវតារក្សត្រ':'1KI','ពង្សាវតារក្សត្រ1':'1KI','2ពង្សាវតា':'2KI','2ពង្សាវតារក្សត្រ':'2KI','ពង្សាវតារក្សត្រ2':'2KI',
 '1របាក្សត្រ':'1CH','របាក្សត្រ1':'1CH','2របាក្សត្រ':'2CH','របាក្សត្រ2':'2CH',
 'ទំនុកតម្កើង':'PSA','ទំនុកដំកើង':'PSA','ទំនុកតំកើង':'PSA','ទំនុកដម្កើង':'PSA','ទំនុកសរសើរ':'PSA',
 '1សាំយូអែល':'1SA','1សាំយ៉ូអែល':'1SA','សាំយូអែល1':'1SA','សាំយ៉ូអែល1':'1SA','2សាំយូអែល':'2SA','2សាំយ៉ូអែល':'2SA','សាំយូអែល2':'2SA','សាំយ៉ូអែល2':'2SA',
 '1ពេត្រុស':'1PE','ពេត្រុស1':'1PE','2ពេត្រុស':'2PE','ពេត្រុស2':'2PE','1យ៉ូហាន':'1JN','យ៉ូហាន1':'1JN','2យ៉ូហាន':'2JN','យ៉ូហាន2':'2JN','3យ៉ូហាន':'3JN','យ៉ូហាន3':'3JN',
 '1ថែស្សាឡូនីច':'1TH','ថែស្សាឡូនីច1':'1TH','2ថែស្សាឡូនីច':'2TH','ថែស្សាឡូនីច2':'2TH','1ធីម៉ូថេ':'1TI','ធីម៉ូថេ1':'1TI','2ធីម៉ូថេ':'2TI','ធីម៉ូថេ2':'2TI',
 'ចោទិយកថា':'DEU','ទុតិយកថា':'DEU','និក្ខមនំ':'EXO','និក្ខមន':'EXO'};Object.entries(extra).forEach(([n,id])=>add(n,id));aliases=[...a.entries()].sort((x,y)=>y[0].length-x[0].length)}
function editDistance(a,b){if(a===b)return 0;if(!a.length)return b.length;if(!b.length)return a.length;let prev=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){const cur=[i];for(let j=1;j<=b.length;j++)cur[j]=Math.min(cur[j-1]+1,prev[j]+1,prev[j-1]+(a[i-1]===b[j-1]?0:1));prev=cur}return prev[b.length]}
function resolveBookToken(token){const t=norm(token);for(const [alias,id] of aliases)if(t===alias)return{id,match:'exact',alias};const lead=t.match(/^([123])(.*)$/),wantNum=lead?.[1]||null;let best=null,second=null;for(const [alias,id] of aliases){const aLead=alias.match(/^([123])(.*)$/);if(wantNum&&aLead?.[1]&&aLead[1]!==wantNum)continue;const d=editDistance(t,alias),limit=Math.max(1,Math.min(3,Math.floor(Math.max(t.length,alias.length)*.2)));if(d>limit)continue;const score=d/Math.max(t.length,alias.length);const item={id,alias,d,score};if(!best||score<best.score||(score===best.score&&d<best.d)){second=best;best=item}else if(!second||score<second.score)second=item}if(best&&(!second||best.id===second.id||second.score-best.score>=.035))return{id:best.id,match:'fuzzy',alias:best.alias,distance:best.d};return null}
function parseRef(q){let n=fromKm(String(q||'')).normalize('NFKC').toLowerCase().replace(/[\u200b\u200c\u200d]/g,'').replace(/[：]/g,':').replace(/[–—−]/g,'-').trim();n=n.replace(/^[•·▪◦*\-]+\s*/,'').replace(/[។៕;,]+\s*$/,'').replace(/\s+/g,'');for(const [alias,id] of aliases){if(!n.startsWith(alias))continue;const rest=n.slice(alias.length),m=rest.match(/^(\d+)(?::(\d+)(?:-(\d+))?)?$/);if(!m)continue;const chapter=+m[1],start=m[2]?+m[2]:1,end=m[3]?+m[3]:start;if(chapter>=1&&chapter<=byId[id].chapterCount&&start>=1&&end>=start)return{book:id,chapter,start,end,match:'exact',inputBook:alias,matchedAlias:alias}}const m=n.match(/^(.*?)(\d+)(?::(\d+)(?:-(\d+))?)?$/);if(!m)return null;const book=resolveBookToken(m[1]);if(!book)return null;const chapter=+m[2],start=m[3]?+m[3]:1,end=m[4]?+m[4]:start;if(chapter<1||chapter>byId[book.id].chapterCount||start<1||end<start)return null;return{book:book.id,chapter,start,end,match:book.match,inputBook:m[1],matchedAlias:book.alias}}
async function passage(ref){const r=parseRef(ref);if(!r)throw Error('មិនស្គាល់លេខយោង: '+ref);const b=await loadBook(r.book),ch=b.chapters[String(r.chapter)],meta=byId[r.book];if(!ch)throw Error('រកមិនឃើញជំពូក');const rows=[];for(let v=r.start;v<=r.end;v++){const t=ch.verses[String(v)];if(t)rows.push({v,text:t})}if(!rows.length)throw Error('រកមិនឃើញខ');return{...r,name:meta.nameKm,reference:`${meta.nameKm} ${toKm(r.chapter)}:${toKm(r.start)}${r.end!==r.start?'–'+toKm(r.end):''}`,rows,text:rows.map(x=>`${toKm(x.v)} ${x.text}`).join('\n')}}
/* project model */
function themeMaster(theme='sunday-dark'){const t=THEMES[theme]||THEMES['sunday-dark'];return{theme,bg:t.bg,fg:t.fg,accent:t.accent,titleFont:fonts.some(f=>f.id==='SONYHEAD5')?'SONYHEAD5':'Krasar',bodyFont:'Krasar',verseNumberStyle:'normal'}}
const PART_LABEL_RE=/\s*\(([០-៩0-9]+)\s*\/\s*([០-៩0-9]+)\)\s*$/;
function pageCounterElement(label,p){return{id:uuid(),type:'text',x:83,y:92,w:12,h:5,rotation:0,opacity:.62,z:30,fontFamily:p?.master?.bodyFont||'Krasar',fontSize:18,color:p?.master?.fg||'#ffffff',fill:'transparent',bold:false,italic:false,align:'right',valign:'bottom',lineHeight:1.15,text:label,ref:'',data:'',role:'pageCounter'}}
function migrateSlideCounter(sl,p){if(!sl||!Array.isArray(sl.elements))return;const refEl=sl.elements.find(e=>e.role==='bibleRef');if(!refEl)return;const mt=String(refEl.text||'').match(PART_LABEL_RE);if(!mt)return;refEl.text=String(refEl.text||'').replace(PART_LABEL_RE,'').trim();if(!sl.elements.some(e=>e.role==='pageCounter'))sl.elements.push(pageCounterElement(`(${mt[1]}/${mt[2]})`,p))}
function normalizeProject(p){if(!p)return p;p.master=p.master||themeMaster('sunday-dark');if(!p.master.verseNumberStyle)p.master.verseNumberStyle='normal';p.slides=Array.isArray(p.slides)?p.slides:[];for(const sl of p.slides){sl.elements=Array.isArray(sl.elements)?sl.elements:[];delete sl.notes;for(const e of sl.elements){if(e.rich)e.rich=sanitizeRichHTML(e.rich)}migrateSlideCounter(sl,p)}return p}
function makeProject(v={}){const now=Date.now(),theme=v.theme||'sunday-dark',master=themeMaster(theme),p={id:v.id||uuid(),title:v.title||'ព្រះបន្ទូលថ្ងៃអាទិត្យ',date:v.date||nextSunday(),service:v.service||'09:30',ratio:v.ratio||'16:9',master,slides:[],createdAt:now,updatedAt:now};const s=makeSlide('Title');s.elements=[Object.assign(makeEl('text',{x:8,y:30,w:84,h:32,text:p.title,fontSize:62,bold:true,align:'center'}),{fontFamily:master.titleFont,color:master.fg})];p.slides=[s];return p}
function makeEl(type,opt={}){const base={id:uuid(),type,x:10,y:20,w:80,h:20,rotation:0,opacity:1,z:1,fontFamily:project?.master?.bodyFont||'Krasar',fontSize:36,color:project?.master?.fg||'#fff',fill:'transparent',bold:false,italic:false,align:'center',valign:'center',text:'',ref:'',data:''};return Object.assign(base,opt)}
function makeSlide(name='Slide'){return{id:uuid(),name,elements:[]}}
function makeTitleSlide(text){const s=makeSlide('Title');s.elements=[makeEl('text',{x:7,y:25,w:86,h:42,text,fontFamily:project?.master?.titleFont||'SONYHEAD5',fontSize:78,bold:true,align:'center',valign:'center',role:'title'})];return s}
function currentSlide(){return project?.slides.find(s=>s.id===slideId)||project?.slides[0]||null}
function currentEl(){return currentSlide()?.elements.find(e=>e.id===elementId)||null}
function ensureSelection(){if(!project)return;slideId=project.slides.some(s=>s.id===slideId)?slideId:project.slides[0]?.id||null;const s=currentSlide();elementId=s?.elements.some(e=>e.id===elementId)?elementId:null;selectedElementIds=new Set([...selectedElementIds].filter(id=>s?.elements.some(e=>e.id===id)));if(elementId&&!selectedElementIds.size)selectedElementIds.add(elementId);selectedSlideIds=new Set([...selectedSlideIds].filter(id=>project.slides.some(sl=>sl.id===id)));if(slideId&&!selectedSlideIds.size)selectedSlideIds.add(slideId)}
/* history + persistence */
function snapshot(){return project?JSON.stringify(project):''}
function pushHistory(){if(!project)return;historyStack.push(snapshot());if(historyStack.length>50)historyStack.shift();redoStack=[];updateUndoUI()}
function updateUndoUI(){$('#undoBtn').disabled=!historyStack.length;$('#redoBtn').disabled=!redoStack.length;const u=$('#rightUndoBtn'),r=$('#rightRedoBtn'),mu=$('#mobileUndoBtn'),mr=$('#mobileRedoBtn');if(u)u.disabled=!historyStack.length;if(r)r.disabled=!redoStack.length;if(mu)mu.disabled=!historyStack.length;if(mr)mr.disabled=!redoStack.length}
function restore(raw){project=normalizeProject(JSON.parse(raw));ensureSelection();selectedSlideIds=new Set(slideId?[slideId]:[]);selectedElementIds.clear();renderAll();scheduleSave()}
function undo(){if(!historyStack.length||!project)return;redoStack.push(snapshot());restore(historyStack.pop());updateUndoUI()}
function redo(){if(!redoStack.length||!project)return;historyStack.push(snapshot());restore(redoStack.pop());updateUndoUI()}
function scheduleSave(){if(!project)return;project.updatedAt=Date.now();$('#saveState').textContent='Saving…';clearTimeout(saveTimer);saveTimer=setTimeout(saveProject,250)}
async function saveProject(){if(!project)return;await idbPut(clone(project));const i=projects.findIndex(p=>p.id===project.id);if(i>=0)projects[i]=clone(project);else projects.push(clone(project));if(window.parent!==window){$('#saveState').textContent='Saved · Finder';mirrorProjectToFinder(project,450);notifyTahoeProjectState("editor");return}$('#saveState').textContent=navigator.onLine&&firebase&&authUser?'Saved · Syncing':'Saved local';clearTimeout(cloudTimer);cloudTimer=setTimeout(saveCloudProject,650)}
async function saveCloudCopy(p){if(window.parent!==window){mirrorProjectToFinder(p,250);return}if(!firebase||!authUser||!navigator.onLine||!p)return;try{const {dbM,db}=firebase;await dbM.set(dbM.ref(db,`${ROOT}/powerslide/${authUser.uid}/projects/${p.id}`),p)}catch(e){console.warn(e)}}
async function saveCloudProject(){if(window.parent!==window){mirrorProjectToFinder(project,200);return}if(!firebase||!authUser||!navigator.onLine||!project)return;try{const {dbM,db}=firebase;await dbM.set(dbM.ref(db,`${ROOT}/powerslide/${authUser.uid}/projects/${project.id}`),project);$('#saveState').textContent='Saved · Synced'}catch(e){console.warn(e);$('#saveState').textContent='Saved · Cloud pending'}}
async function deleteProject(id){await idbDelete(id);projects=projects.filter(p=>p.id!==id);if(window.parent!==window)finderRequest("delete",{projectId:id});else if(firebase&&authUser&&navigator.onLine)firebase.dbM.remove(firebase.dbM.ref(firebase.db,`${ROOT}/powerslide/${authUser.uid}/projects/${id}`)).catch(()=>{});renderLibrary()}
async function openProject(id){project=normalizeProject(clone(projects.find(p=>p.id===id)));if(!project)return;slideId=project.slides[0]?.id||null;elementId=null;selectedSlideIds=new Set(slideId?[slideId]:[]);selectedElementIds.clear();slideAnchorId=slideId;historyStack=[];redoStack=[];$('#libraryView').classList.add('hidden');$('#editorView').classList.remove('hidden');renderAll();scheduleSave()}
async function newProject(){const p=makeProject({title:$('#newTitle').value.trim()||'ព្រះបន្ទូលថ្ងៃអាទិត្យ',date:$('#newDate').value||nextSunday(),service:$('#newService').value.trim(),ratio:$('#newRatio').value,theme:$('#newTheme').value});projects.push(p);await idbPut(p);mirrorProjectToFinder(p,50);closeDlg('newProjectDlg');openProject(p.id)}
function duplicateProject(p){const n=clone(p);n.id=uuid();n.title=p.title+' Copy';n.createdAt=n.updatedAt=Date.now();n.slides.forEach(s=>{s.id=uuid();s.elements.forEach(e=>e.id=uuid())});projects.push(n);idbPut(n).then(()=>{mirrorProjectToFinder(n,50);renderLibrary()})}
function exportProject(p){const blob=new Blob([JSON.stringify(p,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${p.date}-${p.title.replace(/[\\/:*?"<>|]/g,'-')}.powerslide.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function importProject(file){try{const p=normalizeProject(JSON.parse(await file.text()));if(!p.id||!Array.isArray(p.slides))throw Error('Invalid Powerslide project');p.id=uuid();p.updatedAt=Date.now();projects.push(p);await idbPut(p);mirrorProjectToFinder(p,50);renderLibrary();toast('បាន Import project')}catch(e){alert('Import មិនបាន: '+e.message)}}
/* library */
function renderLibrary(){
 applyProjectSidebarWidth();
 const q=norm($('#projectSearch').value);
 const list=projects.map(normalizeProject)
   .filter(p=>!q||norm(`${p.title}${p.date}${p.service}`).includes(q))
   .sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0));
 if(!list.some(p=>p.id===libraryProjectId))libraryProjectId=list[0]?.id||null;

 const totalSlides=list.reduce((n,p)=>n+(p.slides?.length||0),0);
 const newest=list[0]?.updatedAt?new Date(list[0].updatedAt):null;
 const recent=newest&&!Number.isNaN(newest.getTime())?newest.toLocaleDateString():'—';

 const rows=list.map(p=>{
   const selected=p.id===libraryProjectId;
   const metaDate=esc(p.date||'No date');
   const modified=esc(new Date(p.updatedAt||0).toLocaleDateString());
   const service=esc(p.service||'No service');
   return `<article class="psProjectRow ${selected?'selected':''}" data-project="${p.id}">
     <div class="psProjectFirst">
       <button class="psProjectIdentity" data-project-select="${p.id}" title="Open project">
         <span class="psProjectIcon">${FILE_ICON}</span>
         <span class="psProjectText">
           <strong>${esc(p.title)}</strong>
           <small>${metaDate}${p.service?` · ${service}`:''} · ${p.slides?.length||0} slides · Modified ${modified}</small>
         </span>
       </button>
       <button class="psProjectOpen" data-act="open">Open</button>
     </div>
     <div class="psProjectSecond">
       <div class="psProjectMeta">
         <span class="psMetaChip">${p.slides?.length||0} slides</span>
         <span class="psMetaChip">${metaDate}</span>
         <span class="psMetaChip">Tahoe Finder</span>
       </div>
       <div class="psProjectActions">
         <button data-act="rename">Rename</button>
         <button data-act="copy">Duplicate</button>
         <button data-act="json">Download</button>
         <button class="danger" data-act="delete">Delete</button>
       </div>
     </div>
   </article>`
 }).join('');

 $('#projectGroups').innerHTML=`<div class="psProjectShell window pro-readonly tahoeAppWindow">
   <aside class="psProjectSidebar sidebar tahoeAppSidebar">
     <div class="psSidebarTop sidebar-top tahoeAppSidebarTop"><div class="psSidebarHead"><strong>Library</strong><button id="psSidebarToggleSide" class="psSidebarToggle" type="button" title="Hide sidebar" aria-label="Hide sidebar"><i class="ri-layout-left-line"></i></button></div></div>
     <div class="psSidebarList">
       <button class="psFolderRow active">
         <span class="psFolderIcon"><i class="ri-folder-3-fill"></i></span>
         <span>Powerslide Projects</span>
         <span class="psFolderCount">${list.length}</span>
       </button>
     </div>
   </aside>
   <div class="psProjectSplit" id="psProjectSplit" title="Resize sidebar"></div>
   <main class="psProjectMain content tahoeAppPage">
     <div class="psProjectSummary">
       <div class="psSummaryCard"><b>${list.length}</b><span>Projects</span></div>
       <div class="psSummaryCard"><b>${totalSlides}</b><span>Total Slides</span></div>
       <div class="psSummaryCard"><b>${recent}</b><span>Last Updated</span></div>
     </div>
     <div class="psProjectList page">
       ${rows?`<section class="psProjectRows">${rows}</section>`:`<div class="psEmpty"><div><i class="ri-slideshow-line"></i><b>No Powerslide projects</b><div>Create a new project or import one.</div></div></div>`}
     </div>
   </main>
 </div>`;
 bindProjectSidebarResize();
 applyProjectSidebarState();
 const sideToggle=$("#psSidebarToggleSide"),topToggle=$("#psSidebarToggleTop");
 if(sideToggle)sideToggle.onclick=toggleProjectSidebar;
 if(topToggle)topToggle.onclick=toggleProjectSidebar;
 notifyTahoeProjectState('library')
}
function showLibrary(){if(project)scheduleSave();$('#libraryView').classList.remove('hidden');$('#editorView').classList.add('hidden');renderLibrary();notifyTahoeProjectState('library')}
/* Firebase */
async function initFirebase(){if(window.parent!==window){applyAccessGate();return}try{const [appM,authM,dbM]=await Promise.all([import('https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js'),import('https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js'),import('https://www.gstatic.com/firebasejs/12.19.0/firebase-database.js')]);const app=appM.initializeApp(FIREBASE,'powerslide');const auth=authM.getAuth(app),dbx=dbM.getDatabase(app);await authM.setPersistence(auth,authM.browserLocalPersistence);firebase={appM,authM,dbM,app,auth,db:dbx};configUnsub=dbM.onValue(dbM.ref(dbx,ROOT+'/config/allowAnonymous'),snap=>{allowAnonymous=snap.exists()?snap.val()===true:true;applyAccessGate()},()=>{allowAnonymous=true;applyAccessGate()});authM.onAuthStateChanged(auth,async u=>{authUser=u;if(!u){if(allowAnonymous){try{await authM.signInAnonymously(auth)}catch{}}applyAccessGate();return}listenCloud();applyAccessGate()})}catch(e){console.warn('Firebase local-only',e);applyAccessGate()}}

function applyAccessGate(){const blocked=window.parent===window&&!allowAnonymous&&(!authUser||authUser.isAnonymous);$('#accessGate').classList.toggle('hidden',!blocked)}
async function powerslideGoogleLogin(){if(!firebase)return toast('Firebase មិនទាន់ភ្ជាប់');const {authM,auth}=firebase,provider=new authM.GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});try{if(auth.currentUser?.isAnonymous){try{await authM.linkWithPopup(auth.currentUser,provider)}catch(e){if(['auth/credential-already-in-use','auth/email-already-in-use','auth/provider-already-linked'].includes(e.code))await authM.signInWithPopup(auth,provider);else throw e}}else await authM.signInWithPopup(auth,provider)}catch(e){console.warn(e);toast('Google login មិនបាន')}}
function listenCloud(){if(cloudUnsub){cloudUnsub();cloudUnsub=null}if(!firebase||!authUser)return;const {dbM,db}=firebase;cloudUnsub=dbM.onValue(dbM.ref(db,`${ROOT}/powerslide/${authUser.uid}/projects`),async snap=>{if(!snap.exists())return;const remote=Object.values(snap.val()||{}).map(normalizeProject);let changed=false;for(const rp of remote){const lp=projects.find(p=>p.id===rp.id);if(!lp||(+rp.updatedAt||0)>(+lp.updatedAt||0)){await idbPut(rp);const i=projects.findIndex(p=>p.id===rp.id);if(i>=0)projects[i]=rp;else projects.push(rp);changed=true}}if(changed){renderLibrary();if(project){const r=projects.find(p=>p.id===project.id);if(r&&r.updatedAt>project.updatedAt&&!saveTimer){project=clone(r);renderAll()}}}},()=>{})}
/* render */
function slideTheme(){const t=THEMES[project.master.theme]||THEMES['sunday-dark'];return{bg:project.master.bg||t.bg,fg:project.master.fg||t.fg,accent:project.master.accent||t.accent}}
function scaledFont(px,container=$('#slideCanvas')){return Math.max(6,px*(container.clientWidth||960)/960)}
function isTextElement(e){return !!e&&['text','bible'].includes(e.type)}
function defaultLineHeight(e){return e?.lineHeight||((e?.type==='bible'||e?.role==='bibleText')?1.42:1.38)}
function applyElStyle(node,e,container=$('#slideCanvas')){node.style.left=e.x+'%';node.style.top=e.y+'%';node.style.width=e.w+'%';node.style.height=e.h+'%';node.style.transform=`rotate(${e.rotation||0}deg)`;node.style.opacity=e.opacity??1;node.style.zIndex=e.z||1;node.style.borderRadius=(e.radius||0)+'px';const c=node.querySelector('.content');if(!c)return;const f=fontBy(e.fontFamily);c.style.fontFamily=f.css;c.style.fontSize=scaledFont(e.fontSize||32,container)+'px';c.style.fontWeight=e.bold?'700':'400';c.style.fontStyle=e.italic?'italic':'normal';c.style.color=e.color||slideTheme().fg;c.style.textAlign=e.align||'left';c.style.justifyContent=e.valign==='top'?'flex-start':e.valign==='bottom'?'flex-end':'center';c.style.alignItems=e.align==='center'?'center':e.align==='right'?'flex-end':'flex-start';c.style.lineHeight=defaultLineHeight(e);c.style.background=e.fill||'transparent'}
function fitElementToBox(node,e,container=$('#slideCanvas')){if(!isTextElement(e)||!node||node.classList.contains('editing'))return;const c=node.querySelector('.content');if(!c||!c.clientWidth||!c.clientHeight)return;const base=scaledFont(e.fontSize||32,container);c.style.fontSize=base+'px';const over=()=>c.scrollHeight>c.clientHeight+1||c.scrollWidth>c.clientWidth+1;if(!over()){node.dataset.fit='100';return}let lo=Math.max(7,base*.38),hi=base,best=lo;c.style.fontSize=lo+'px';for(let i=0;i<9;i++){const mid=(lo+hi)/2;c.style.fontSize=mid+'px';if(over())hi=mid;else{best=mid;lo=mid}}c.style.fontSize=best+'px';node.dataset.fit=String(Math.round(best/base*100))}
function styleAndFit(node,e,container){applyElStyle(node,e,container);requestAnimationFrame(()=>fitElementToBox(node,e,container))}
function isDarkColor(hex){const x=String(hex||'#000').replace('#','');if(!/^[0-9a-f]{6}$/i.test(x))return true;const r=parseInt(x.slice(0,2),16),g=parseInt(x.slice(2,4),16),b=parseInt(x.slice(4,6),16);return(.2126*r+.7152*g+.0722*b)<150}
function verseNumberColor(bg){return isDarkColor(bg)?'#ffd84d':'#1769ff'}
function bibleTextHTML(text,thumb=false){let raw=String(text||'');if(thumb)raw=raw.slice(0,150);const lines=raw.split(/\n+/).filter(x=>x.trim());if(!lines.length)return '';const mode=project?.master?.verseNumberStyle==='superscript'?'superscript':'normal';return `<div class="verseBlock">${lines.map(line=>{const m=line.match(/^\s*([០-៩0-9]+)\s+(.*)$/);return m?`<span class="verseLine"><span class="verseNo ${mode}">${esc(m[1])}</span> <span class="verseText">${esc(m[2])}</span></span>`:`<span class="verseLine"><span class="verseText">${esc(line)}</span></span>`}).join('')}</div>`}
function elementInner(e,thumb=false){if(e.type==='image')return `<img src="${e.data}" alt="">`;if(e.type==='shape')return '';if(e.type==='bible'){const body=e.rich?sanitizeRichHTML(e.rich):bibleTextHTML(e.text,thumb);return `<div class="bibleObjectRef" style="font-size:.62em;font-weight:700;color:${esc(project.master.accent)};margin-bottom:.35em">${esc(e.ref||'Bible')}</div>${body}`}if(e.role==='bibleText')return e.rich?sanitizeRichHTML(e.rich):bibleTextHTML(e.text,thumb);if(e.rich)return sanitizeRichHTML(e.rich);return esc(thumb?(e.text||'').slice(0,120):e.text||'')}
function renderCanvas(){const s=currentSlide(),c=$('#slideCanvas');if(!s)return;c.classList.toggle('ratio43',project.ratio==='4:3');c.classList.toggle('gridOn',gridOn);const th=slideTheme();c.style.background=th.bg;c.style.setProperty('--verse-number-color',verseNumberColor(th.bg));c.innerHTML='<div class="safeArea"></div>'+[...s.elements].sort((a,b)=>(a.z||1)-(b.z||1)).map(e=>`<div class="slide-element ${selectedElementIds.has(e.id)||e.id===elementId?'selected':''} ${e.id===elementId?'primarySelected':''}" data-id="${e.id}" data-type="${e.type}" data-role="${esc(e.role||'')}"><div class="content">${elementInner(e)}</div>${e.id===elementId?`<div class="selectionLabel">${esc(e.type)} · double-click text to edit</div><div class="rotateLine"></div><div class="rotateHandle" data-rotate></div><div class="resizeHandle" data-resize></div>`:''}</div>`).join('');c.querySelectorAll('.slide-element').forEach(n=>{const e=s.elements.find(x=>x.id===n.dataset.id);applyElStyle(n,e,c);fitElementToBox(n,e,c)});bindInlineEditing(c)}
function scrollActiveThumbIntoView(behavior='smooth'){const active=$('#slideList .thumbRow.active');active?.scrollIntoView({block:'nearest',behavior})}
function renderThumbs(){const list=$('#slideList');if(!project||!list)return;const th=slideTheme();list.replaceChildren();project.slides.forEach((s,i)=>{const row=document.createElement('div');const picked=selectedSlideIds.has(s.id),active=s.id===slideId;row.className=`thumbRow ${active?'active':''} ${picked?'multiSelected':''}`;row.dataset.slide=s.id;row.draggable=true;row.innerHTML=`<div class="thumbNo">${toKm(i+1)}</div><div class="thumb ${project.ratio==='4:3'?'ratio43':''} ${active?'active':''}" style="background:${th.bg};--verse-number-color:${verseNumberColor(th.bg)}"><div class="thumbMini"></div>${picked&&selectedSlideIds.size>1?`<span class="thumbSelectBadge">✓</span>`:''}</div>`;list.appendChild(row);const mini=row.querySelector('.thumbMini');mini.innerHTML=[...s.elements].sort((a,b)=>(a.z||1)-(b.z||1)).map(e=>`<div class="thumbEl" data-id="${e.id}" data-type="${e.type}" data-role="${esc(e.role||'')}"><div class="content">${elementInner(e)}</div></div>`).join('');mini.querySelectorAll('.thumbEl').forEach(n=>{const e=s.elements.find(x=>x.id===n.dataset.id);applyElStyle(n,e,mini);fitElementToBox(n,e,mini)})});requestAnimationFrame(()=>scrollActiveThumbIntoView('auto'))}
function selectOnlySlide(id,opt={}){selectedSlideIds=new Set(id?[id]:[]);slideAnchorId=id;setSlide(id,{...opt,preserveSelection:true})}
function toggleSlideSelection(id){if(selectedSlideIds.has(id)&&selectedSlideIds.size>1)selectedSlideIds.delete(id);else selectedSlideIds.add(id);slideAnchorId=id;slideId=id;elementId=null;selectedElementIds.clear();renderAll();requestAnimationFrame(()=>scrollActiveThumbIntoView('smooth'))}
function rangeSelectSlides(id){const a=project.slides.findIndex(s=>s.id===slideAnchorId),b=project.slides.findIndex(s=>s.id===id);if(a<0||b<0)return selectOnlySlide(id);selectedSlideIds=new Set(project.slides.slice(Math.min(a,b),Math.max(a,b)+1).map(s=>s.id));slideId=id;elementId=null;selectedElementIds.clear();renderAll();requestAnimationFrame(()=>scrollActiveThumbIntoView('smooth'))}
function selectAllSlides(){selectedSlideIds=new Set(project.slides.map(s=>s.id));if(!slideId)slideId=project.slides[0]?.id||null;renderThumbs();toast(`${selectedSlideIds.size} slides selected`)}
function duplicateSelectedSlides(){const chosen=selectedSlides();if(!chosen.length)return duplicateSlide();pushHistory();const ids=new Set(chosen.map(s=>s.id)),out=[],copies=[];for(const sl of project.slides){out.push(sl);if(ids.has(sl.id)){const n=clone(sl);n.id=uuid();n.name=sl.name+' Copy';n.elements.forEach(e=>e.id=uuid());out.push(n);copies.push(n)}}project.slides=out;selectedSlideIds=new Set(copies.map(s=>s.id));slideId=copies[0]?.id||slideId;slideAnchorId=slideId;elementId=null;selectedElementIds.clear();renderAll();scheduleSave()}
function deleteSelectedSlides(){const ids=new Set(selectedSlideIds.size?selectedSlideIds:[slideId]);if(project.slides.length-ids.size<1)return toast('Project ត្រូវមានយ៉ាងហោចណាស់ ១ slide');if(!confirm(`Delete ${ids.size} selected slide${ids.size>1?'s':''}?`))return;pushHistory();const oldIndex=project.slides.findIndex(s=>ids.has(s.id));project.slides=project.slides.filter(s=>!ids.has(s.id));slideId=project.slides[Math.max(0,Math.min(oldIndex,project.slides.length-1))]?.id||project.slides[0].id;selectedSlideIds=new Set([slideId]);elementId=null;selectedElementIds.clear();renderAll();scheduleSave()}
function reorderSelectedSlides(targetId,after=false){const moving=project.slides.filter(s=>selectedSlideIds.has(s.id));if(!moving.length||selectedSlideIds.has(targetId))return;pushHistory();const rest=project.slides.filter(s=>!selectedSlideIds.has(s.id));let idx=rest.findIndex(s=>s.id===targetId);if(idx<0)return;if(after)idx++;rest.splice(idx,0,...moving);project.slides=rest;slideId=moving[0].id;renderAll();scheduleSave()}
function propOptions(value){return fonts.map(f=>`<option value="${esc(f.id)}" ${f.id===value?'selected':''}>${esc(f.name)}</option>`).join('')}
function alignIcon(kind){const paths={left:'M3.75 6.75h16.5M3.75 12h10.5M3.75 17.25h16.5',center:'M3.75 6.75h16.5M6.75 12h10.5M3.75 17.25h16.5',right:'M3.75 6.75h16.5M9.75 12h10.5M3.75 17.25h16.5',justify:'M3.75 6.75h16.5M3.75 12h16.5M3.75 17.25h16.5',top:'M4.5 5.25h15m-7.5 3v10.5m0-10.5-3 3m3-3 3 3',middle:'M4.5 12h15m-7.5-6.75v13.5m0-6.75-3-3m3 3 3-3',bottom:'M4.5 18.75h15m-7.5-13.5v10.5m0 0-3-3m3 3 3-3'};return hero(paths[kind]||paths.left)}
function renderInspector(){const e=currentEl(),box=$('#inspectorBody'),many=selectedElementIds.size>1;if(!e){box.innerHTML='<div class="emptyInspector">ជ្រើសរើសធាតុនៅលើ slide ដើម្បីកែសម្រួល។<br><br><b>Cmd/Ctrl + click</b> ដើម្បីជ្រើសរើសច្រើន។<br><b>Cmd/Ctrl + A</b> ដើម្បី Select All នៅលើ slide។</div>';return}box.innerHTML=`
 <div class="propSection"><div class="propTitle">${many?`${selectedElementIds.size} OBJECTS`:esc(e.type.toUpperCase())}</div>
 ${e.type==='bible'&&!many?`<label class="field"><span>Bible reference</span><input data-prop="ref" value="${esc(e.ref)}"></label><button id="refreshBible" class="btn fullBtn">Refresh from Bible1954</button>`:''}
 ${isTextElement(e)?`<div class="richEditBar"><button class="richBtn ${e.bold?'active':''}" data-rich="bold" title="Bold selected text"><b>B</b></button><label class="richColorBtn" title="Text color"><input id="richTextColor" type="color" value="${e.color||'#ffffff'}"><span>A</span></label><label class="richColorBtn highlighter" title="Highlight selected text"><input id="richHighlight" type="color" value="#ffe066"><span>▰</span></label></div><label class="field"><span>${many?'Font for selected objects':'Khmer font / selected text'}</span><select id="richFont">${propOptions(e.fontFamily)}</select></label><div class="alignToolbar"><button data-align="left" class="${e.align==='left'?'active':''}" title="Align left">${alignIcon('left')}</button><button data-align="center" class="${e.align==='center'?'active':''}" title="Center">${alignIcon('center')}</button><button data-align="right" class="${e.align==='right'?'active':''}" title="Align right">${alignIcon('right')}</button><button data-align="justify" class="${e.align==='justify'?'active':''}" title="Justify">${alignIcon('justify')}</button></div><div class="alignToolbar verticalAlign"><button data-valign="top" class="${e.valign==='top'?'active':''}" title="Top">${alignIcon('top')}</button><button data-valign="center" class="${!e.valign||e.valign==='center'?'active':''}" title="Middle">${alignIcon('middle')}</button><button data-valign="bottom" class="${e.valign==='bottom'?'active':''}" title="Bottom">${alignIcon('bottom')}</button></div>${!many?`<label class="field"><span>Text</span><textarea data-prop="text">${esc(e.text)}</textarea></label><button id="editDirectTextBtn" class="btn fullBtn">✎ Edit directly on slide</button>`:''}<div class="row2"><label class="field"><span>Size</span><input type="number" min="8" max="180" data-prop="fontSize" value="${e.fontSize}"></label><label class="field"><span>Color</span><input type="color" data-prop="color" value="${e.color||'#ffffff'}"></label></div><div class="batchActions"><button id="applySelectedFontAll" class="btn">Font → ALL slides</button><button id="boldAllText" class="btn">Bold ALL</button><button id="unboldAllText" class="btn">Unbold ALL</button></div>`:''}
 ${e.type==='shape'&&!many?`<label class="field"><span>Fill</span><input type="color" data-prop="fill" value="${e.fill==='transparent'?'#ffffff':e.fill}"></label><label class="field"><span>Corner radius</span><input type="range" min="0" max="80" data-prop="radius" value="${e.radius||0}"></label>`:''}
 ${!many?`<div class="propSection" style="margin-top:12px"><div class="propTitle">Position / Size</div><div class="row4">${['x','y','w','h'].map(k=>`<label class="field"><span>${k.toUpperCase()}</span><input type="number" step=".1" data-prop="${k}" value="${(+e[k]).toFixed(1)}"></label>`).join('')}</div><div class="row2"><label class="field"><span>Rotation</span><input type="number" data-prop="rotation" value="${e.rotation||0}"></label><label class="field"><span>Opacity</span><input type="number" min="0" max="1" step=".05" data-prop="opacity" value="${e.opacity??1}"></label></div></div>`:''}
 <div class="propSection"><div class="propTitle">Layer</div><div class="layerActions"><button data-layer="up">Bring forward</button><button data-layer="down">Send backward</button><button data-layer="duplicate">Duplicate</button><button data-layer="delete">Delete</button></div></div>`;
 const applyBatch=(k,v)=>{const els=selectedTextElements();if(!els.length)return;pushHistory();for(const el of els)el[k]=v;renderAll();scheduleSave()};
 box.querySelectorAll('[data-prop]').forEach(x=>x.oninput=()=>{const k=x.dataset.prop,v=['fontSize','x','y','w','h','rotation','opacity','radius'].includes(k)?+x.value:x.value;if(many&&['fontFamily','fontSize','color'].includes(k))return applyBatch(k,v);const el=currentEl();if(!el)return;pushHistory();el[k]=v;if(k==='text')el.rich='';renderCanvas();renderThumbs();scheduleSave()});
 box.querySelectorAll('[data-align]').forEach(x=>x.onpointerdown=ev=>{ev.preventDefault();applyTextFormat('align',x.dataset.align)});box.querySelectorAll('[data-valign]').forEach(x=>x.onclick=()=>applyBatch('valign',x.dataset.valign));box.querySelectorAll('[data-layer]').forEach(x=>x.onclick=()=>layerAction(x.dataset.layer));
 const rb=$('#refreshBible');if(rb)rb.onclick=refreshSelectedBible;const ed=$('#editDirectTextBtn');if(ed)ed.onclick=()=>{const el=currentEl();if(el)startInlineEdit(el.id)};const af=$('#applySelectedFontAll');if(af)af.onclick=()=>applyFontToAll(currentEl()?.fontFamily);const bf=$('#boldAllText');if(bf)bf.onclick=()=>setAllBold(true);const ub=$('#unboldAllText');if(ub)ub.onclick=()=>setAllBold(false);const bb=box.querySelector('[data-rich="bold"]');if(bb)bb.onpointerdown=ev=>{ev.preventDefault();applyTextFormat('bold')};const tc=$('#richTextColor');if(tc)tc.oninput=()=>applyTextFormat('color',tc.value);const hc=$('#richHighlight');if(hc)hc.oninput=()=>applyTextFormat('highlight',hc.value);const rf=$('#richFont');if(rf)rf.onchange=()=>applyTextFormat('font',rf.value)}
function renderAll(){if(!project)return;ensureSelection();$('#projectTitle').value=project.title;renderThumbs();renderCanvas();renderInspector();updateGlobalButtons();updateUndoUI();notifyTahoeProjectState('editor')}
function setSlide(id,opt={}){slideId=id;elementId=null;selectedElementIds.clear();if(!opt.preserveSelection){selectedSlideIds=new Set(id?[id]:[]);slideAnchorId=id}renderAll();if(opt.scroll!==false)requestAnimationFrame(()=>scrollActiveThumbIntoView(opt.behavior||'smooth'))}
function stepEditor(delta){if(!project?.slides?.length)return;let i=project.slides.findIndex(s=>s.id===slideId);if(i<0)i=0;i=Math.max(0,Math.min(project.slides.length-1,i+delta));setSlide(project.slides[i].id,{behavior:'smooth'})}
function edgeEditor(which){if(!project?.slides?.length)return;setSlide(project.slides[which==='end'?project.slides.length-1:0].id,{behavior:'smooth'})}
function selectElement(id,opt={}){if(!opt.additive)selectedElementIds=new Set([id]);else if(selectedElementIds.has(id)&&selectedElementIds.size>1)selectedElementIds.delete(id);else selectedElementIds.add(id);elementId=id;selectionScope='canvas';if(innerWidth<=900)$('#editorView')?.classList.remove('mobilePropsCollapsed');renderCanvas();renderInspector()}
function layerAction(a){const s=currentSlide(),e=currentEl();if(!s||!e)return;pushHistory();const chosen=selectedElements();if(a==='up')for(const x of chosen)x.z=Math.max(...s.elements.map(q=>q.z||1))+1;else if(a==='down')for(const x of chosen)x.z=Math.min(...s.elements.map(q=>q.z||1))-1;else if(a==='duplicate'){const copies=chosen.map(x=>{const n=clone(x);n.id=uuid();n.x=Math.min(95-n.w,n.x+2);n.y=Math.min(95-n.h,n.y+2);n.z=(x.z||1)+1;s.elements.push(n);return n});selectedElementIds=new Set(copies.map(x=>x.id));elementId=copies[0]?.id||null}else if(a==='delete'){const ids=new Set(chosen.map(x=>x.id));s.elements=s.elements.filter(x=>!ids.has(x.id));elementId=null;selectedElementIds.clear()}renderAll();scheduleSave()}
/* rich text + multi-object formatting */
function rememberTextRange(){const sel=getSelection();if(!inlineEditId||!sel||!sel.rangeCount)return;const target=document.querySelector(`.slide-element[data-id="${inlineEditId}"] [contenteditable="true"]`);if(!target||!target.contains(sel.anchorNode)||!target.contains(sel.focusNode))return;savedTextRange=sel.getRangeAt(0).cloneRange()}
function restoreTextRange(){if(!savedTextRange)return false;const sel=getSelection();try{sel.removeAllRanges();sel.addRange(savedTextRange);return true}catch{return false}}
function hasRichSelection(){if(!inlineEditId||!savedTextRange||savedTextRange.collapsed)return false;return true}
function syncInlineRich(){const e=currentEl(),node=document.querySelector(`.slide-element[data-id="${inlineEditId}"]`),target=editingTarget(node,e);if(!e||!target)return;e.rich=sanitizeRichHTML(target.innerHTML);e.text=plainFromRich(e.rich);renderThumbs();scheduleSave()}
function applyWholeRichStyle(el,kind,value){if(!isTextElement(el))return;if(kind==='bold'){el.bold=!el.bold;return}if(kind==='font'){el.fontFamily=value;return}if(kind==='color'){el.color=value;return}if(kind==='align'){el.align=value;return}let base=el.rich||elementInner(el);if(kind==='highlight')el.rich=sanitizeRichHTML(`<span style="background-color:${value}">${base}</span>`)}
function applyTextFormat(kind,value){if(hasRichSelection()&&restoreTextRange()){const cmd=kind==='bold'?'bold':kind==='font'?'fontName':kind==='color'?'foreColor':kind==='highlight'?'hiliteColor':kind==='align'?({left:'justifyLeft',center:'justifyCenter',right:'justifyRight',justify:'justifyFull'}[value]||'justifyLeft'):null;if(cmd){document.execCommand(cmd,false,kind==='font'?fontBy(value).family:(value||null));rememberTextRange();syncInlineRich();return}}const els=selectedTextElements();if(!els.length&&currentEl()&&isTextElement(currentEl()))els.push(currentEl());if(!els.length)return;pushHistory();for(const el of els)applyWholeRichStyle(el,kind,value);renderAll();scheduleSave()}
function stripBoldRich(html){const d=document.createElement('div');d.innerHTML=html||'';d.querySelectorAll('b,strong').forEach(n=>n.replaceWith(...n.childNodes));d.querySelectorAll('[style]').forEach(n=>{n.style.fontWeight='';if(!n.getAttribute('style'))n.removeAttribute('style')});return sanitizeRichHTML(d.innerHTML)}
function setAllBold(on){if(!project)return;pushHistory();for(const s of project.slides)for(const e of s.elements)if(isTextElement(e)){e.bold=!!on;if(!on&&e.rich)e.rich=stripBoldRich(e.rich)}renderAll();scheduleSave();toast(on?'All text bold':'All text unbold')}
/* editor actions */
function addSlide(template='blank'){pushHistory();let s=makeSlide(template==='title'?'Title':'Slide');if(template==='title')s.elements=[makeEl('text',{x:8,y:30,w:84,h:30,text:'ចំណងជើង',fontFamily:project.master.titleFont,fontSize:60,bold:true,align:'center'})];project.slides.push(s);slideId=s.id;selectedSlideIds=new Set([s.id]);slideAnchorId=s.id;elementId=null;selectedElementIds.clear();renderAll();scheduleSave()}
function duplicateSlide(){const s=currentSlide();if(!s)return;pushHistory();const n=clone(s);n.id=uuid();n.name=s.name+' Copy';n.elements.forEach(e=>e.id=uuid());const i=project.slides.findIndex(x=>x.id===s.id);project.slides.splice(i+1,0,n);slideId=n.id;selectedSlideIds=new Set([n.id]);slideAnchorId=n.id;elementId=null;selectedElementIds.clear();renderAll();scheduleSave()}
function deleteSlide(){if(project.slides.length<=1)return toast('Project ត្រូវមានយ៉ាងហោចណាស់ ១ slide');const s=currentSlide();if(!confirm('Delete this slide?'))return;pushHistory();const i=project.slides.findIndex(x=>x.id===s.id);project.slides.splice(i,1);slideId=project.slides[Math.max(0,i-1)].id;selectedSlideIds=new Set([slideId]);slideAnchorId=slideId;elementId=null;selectedElementIds.clear();renderAll();scheduleSave()}
function addText(){pushHistory();const e=makeEl('text',{x:10,y:28,w:80,h:34,text:'សរសេរអត្ថបទនៅទីនេះ',fontFamily:project.master.bodyFont,fontSize:54,color:project.master.fg,align:'center',valign:'center',bold:false,z:10,role:'body'});currentSlide().elements.push(e);elementId=e.id;if(innerWidth<=900)$('#editorView')?.classList.remove('mobilePropsCollapsed');renderAll();scheduleSave()}
function addShape(){pushHistory();const e=makeEl('shape',{x:25,y:32,w:50,h:28,fill:project.master.accent,opacity:.25,radius:18,z:1});currentSlide().elements.push(e);elementId=e.id;if(innerWidth<=900)$('#editorView')?.classList.remove('mobilePropsCollapsed');renderAll();scheduleSave()}
function addImageFile(file){if(!file)return;const r=new FileReader();r.onload=()=>{pushHistory();const e=makeEl('image',{x:20,y:18,w:60,h:64,data:r.result,z:5});currentSlide().elements.push(e);elementId=e.id;renderAll();scheduleSave()};r.readAsDataURL(file)}
async function addBible(ref){try{const p=await passage(ref);pushHistory();const e=makeEl('bible',{x:7,y:11,w:86,h:78,ref:p.reference,text:p.text,fontFamily:project.master.bodyFont,fontSize:p.text.length>650?42:p.text.length>380?48:56,color:project.master.fg,align:'left',valign:'center',z:10,role:'bible'});currentSlide().elements.push(e);elementId=e.id;renderAll();scheduleSave();return true}catch(e){$('#biblePreview').textContent=e.message;return false}}
async function refreshSelectedBible(){const e=currentEl();if(!e||e.type!=='bible')return;try{const p=await passage(e.ref);pushHistory();e.ref=p.reference;e.text=p.text;e.rich='';renderAll();scheduleSave();toast('បាន Refresh ពី Bible1954')}catch(err){toast(err.message)}}
/* direct canvas editing */
function editingTarget(node,e){if(!node||!e||!['text','bible'].includes(e.type))return null;if(e.type==='bible'||e.role==='bibleText')return node.querySelector('.verseBlock')||node.querySelector('.content');return node.querySelector('.content')}
function placeCaretEnd(el){try{const r=document.createRange(),s=window.getSelection();r.selectNodeContents(el);r.collapse(false);s.removeAllRanges();s.addRange(r)}catch{}}
function startInlineEdit(id){const e=currentSlide()?.elements.find(x=>x.id===id);if(!e||!editingTarget(document.querySelector(`.slide-element[data-id="${id}"]`),e))return;inlineEditId=null;elementId=id;renderCanvas();renderInspector();const canvas=$('#slideCanvas'),fresh=canvas.querySelector(`.slide-element[data-id="${id}"]`),target=editingTarget(fresh,e);if(!fresh||!target)return;pushHistory();inlineEditId=id;fresh.classList.add('editing');target.setAttribute('contenteditable','true');target.setAttribute('spellcheck','false');target.focus({preventScroll:true});placeCaretEnd(target);const save=()=>{if(inlineEditId!==id)return;e.rich=sanitizeRichHTML(target.innerHTML);e.text=plainFromRich(e.rich);applyElStyle(fresh,e,canvas);fitElementToBox(fresh,e,canvas);renderThumbs();renderInspector();scheduleSave()};target.addEventListener('input',()=>{save();rememberTextRange()});target.addEventListener('keyup',rememberTextRange);target.addEventListener('mouseup',rememberTextRange);target.addEventListener('keydown',k=>{if(k.key==='Escape'){k.preventDefault();target.blur()}if((k.metaKey||k.ctrlKey)&&k.key==='Enter'){k.preventDefault();target.blur()}});target.addEventListener('blur',()=>{save();inlineEditId=null;savedTextRange=null;renderCanvas()},{once:true})}
function bindInlineEditing(canvas){canvas.ondblclick=ev=>{const node=ev.target.closest('.slide-element');if(!node)return;ev.preventDefault();ev.stopPropagation();startInlineEdit(node.dataset.id)}}
function applyFontToAll(fontId){if(!project||!fontId)return;pushHistory();project.master.titleFont=fontId;project.master.bodyFont=fontId;for(const s of project.slides)for(const e of s.elements)if(['text','bible'].includes(e.type))e.fontFamily=fontId;renderAll();scheduleSave();toast('Font applied to ALL slides')}
function toggleVerseStyle(){if(!project)return;pushHistory();project.master.verseNumberStyle=project.master.verseNumberStyle==='superscript'?'normal':'superscript';renderAll();renderDesign();scheduleSave();toast(project.master.verseNumberStyle==='superscript'?'Verse numbers: superscript':'Verse numbers: normal')}
function updateGlobalButtons(){if(!project)return;const sup=project.master.verseNumberStyle==='superscript',b=$('#verseStyleBtn'),d=$('#designVerseStyleBtn');if(b)b.textContent=sup?'¹ Verse: Superscript':'¹ Verse: Normal';if(d)d.textContent=sup?'Verse No: Superscript':'Verse No: Normal'}
/* dragging */
function beginDrag(ev,node){if(node.classList.contains('editing')||ev.target.closest('[contenteditable="true"]'))return;const e=currentSlide().elements.find(x=>x.id===node.dataset.id);if(!e)return;const mode=ev.target.closest('[data-resize]')?'resize':ev.target.closest('[data-rotate]')?'rotate':'move',now=performance.now();if((ev.metaKey||ev.ctrlKey)&&mode==='move'){selectElement(e.id,{additive:true});ev.preventDefault();return}if(mode==='move'&&lastElementTap.id===e.id&&now-lastElementTap.time<430){lastElementTap={id:null,time:0};ev.preventDefault();ev.stopPropagation();startInlineEdit(e.id);return}lastElementTap={id:e.id,time:now};if(!selectedElementIds.has(e.id))selectElement(e.id);pushHistory();const rect=$('#slideCanvas').getBoundingClientRect(),start={x:ev.clientX,y:ev.clientY,e:clone(e),all:Object.fromEntries(selectedElements().map(x=>[x.id,clone(x)]))};drag={mode,rect,start,id:e.id};node.setPointerCapture?.(ev.pointerId);ev.preventDefault()}
function moveDrag(ev){if(!drag)return;const e=currentSlide().elements.find(x=>x.id===drag.id);if(!e)return;const dx=(ev.clientX-drag.start.x)/drag.rect.width*100,dy=(ev.clientY-drag.start.y)/drag.rect.height*100,o=drag.start.e;if(drag.mode==='move'){for(const x of selectedElements()){const st=drag.start.all[x.id]||clone(x);x.x=Math.max(0,Math.min(100-x.w,st.x+dx));x.y=Math.max(0,Math.min(100-x.h,st.y+dy))}}else if(drag.mode==='resize'){e.w=Math.max(2,Math.min(100-e.x,o.w+dx));e.h=Math.max(2,Math.min(100-e.y,o.h+dy))}else{const cx=drag.rect.left+(e.x+e.w/2)/100*drag.rect.width,cy=drag.rect.top+(e.y+e.h/2)/100*drag.rect.height;e.rotation=Math.round(Math.atan2(ev.clientY-cy,ev.clientX-cx)*180/Math.PI+90)}renderCanvas();renderInspector()}
function endDrag(){if(!drag)return;drag=null;renderThumbs();scheduleSave()}
/* smart generator */
function titleSlide(text){const s=makeSlide('Section');s.elements=[makeEl('text',{x:7,y:22,w:86,h:50,text,fontFamily:project.master.titleFont,fontSize:text.length>45?64:82,bold:true,color:project.master.fg,align:'center',valign:'center',z:10,role:'title'})];return s}
function textSlide(title,body){const s=makeSlide('Text');s.elements=[];if(title)s.elements.push(makeEl('text',{x:7,y:7,w:86,h:15,text:title,fontFamily:project.master.titleFont,fontSize:48,bold:true,color:project.master.accent,align:'center',valign:'center',z:10,role:'subtitle'}));s.elements.push(makeEl('text',{x:8,y:title?25:15,w:84,h:title?66:76,text:body,fontFamily:project.master.bodyFont,fontSize:body.length>450?40:body.length>260?46:54,color:project.master.fg,align:'left',valign:'center',z:10,role:'body'}));return s}
function bibleSlide(ref,text,partLabel=''){const s=makeSlide('Bible');s.elements=[makeEl('text',{x:7,y:7,w:86,h:12,text:ref,fontFamily:project.master.titleFont,fontSize:42,bold:true,color:project.master.accent,align:'center',valign:'center',z:10,role:'bibleRef'}),makeEl('text',{x:7,y:21,w:86,h:67,text,fontFamily:project.master.bodyFont,fontSize:text.length>650?42:text.length>420?48:text.length>240?54:60,color:project.master.fg,align:'left',valign:'center',z:10,role:'bibleText'})];if(partLabel)s.elements.push(pageCounterElement(partLabel,project));return s}
function splitPassageRows(p){const chunks=[];let cur=[],chars=0;for(const r of p.rows){const line=`${toKm(r.v)} ${r.text}`;if(cur.length&&(cur.length>=4||chars+line.length>560)){chunks.push(cur);cur=[];chars=0}cur.push(line);chars+=line.length}if(cur.length)chunks.push(cur);return chunks}
/* manual Bible-slide splitting from thumbnail context menu */
function bibleBodyElement(slide){return slide?.elements?.find(e=>e.role==='bibleText')||slide?.elements?.find(e=>e.type==='bible')||null}
function bibleRefElement(slide){return slide?.elements?.find(e=>e.role==='bibleRef')||null}
function counterElement(slide){return slide?.elements?.find(e=>e.role==='pageCounter')||null}
function verseRowsFromSlide(slide){const e=bibleBodyElement(slide);if(!e)return[];return String(e.text||'').split(/\n+/).map(x=>x.trim()).filter(Boolean).map(line=>{const m=line.match(/^([០-៩0-9]+)\s+(.*)$/);return m?{line,no:fromKm(m[1]),text:m[2]}:null}).filter(Boolean)}
function splitCounterParts(slide){const c=counterElement(slide);if(!c)return null;const m=String(c.text||'').match(/\(([០-៩0-9]+)\s*\/\s*([០-៩0-9]+)\)/);return m?{index:+fromKm(m[1]),total:+fromKm(m[2])}:null}
function sameBibleSplitFamily(a,b){if(!a||!b)return false;const ar=bibleRefElement(a),br=bibleRefElement(b);if(!ar||!br||norm(ar.text)!==norm(br.text))return false;return !!counterElement(a)&&!!counterElement(b)}
function splitFamilyRange(index){let start=index,end=index;const slides=project?.slides||[];if(!counterElement(slides[index]))return{start,end};while(start>0&&sameBibleSplitFamily(slides[start-1],slides[index]))start--;while(end+1<slides.length&&sameBibleSplitFamily(slides[end+1],slides[index]))end++;return{start,end}}
function balancedVerseGroups(rows,parts){const n=rows.length,k=Math.max(1,Math.min(parts,n));if(k===1)return[rows];const weights=rows.map(r=>Math.max(20,r.line.length+12)),prefix=[0];weights.forEach(w=>prefix.push(prefix[prefix.length-1]+w));const total=prefix[n],target=total/k,INF=1e30,dp=Array.from({length:k+1},()=>Array(n+1).fill(INF)),prev=Array.from({length:k+1},()=>Array(n+1).fill(-1));dp[0][0]=0;for(let g=1;g<=k;g++){for(let i=g;i<=n;i++){for(let j=g-1;j<i;j++){const sum=prefix[i]-prefix[j],cost=dp[g-1][j]+Math.pow(sum-target,2);if(cost<dp[g][i]){dp[g][i]=cost;prev[g][i]=j}}}}const out=[];let i=n;for(let g=k;g>=1;g--){const j=prev[g][i];out.unshift(rows.slice(j,i));i=j}return out}
function idealBibleFont(text){const n=String(text||'').length;return n>700?44:n>520?48:n>360?52:n>240?56:n>140?60:64}
function cloneSlidePiece(slide,rows){const n=clone(slide);n.id=uuid();n.elements.forEach(e=>e.id=uuid());n.elements=n.elements.filter(e=>e.role!=='pageCounter');const body=bibleBodyElement(n);if(body){body.text=rows.map(r=>r.line).join('\n');body.fontSize=Math.max(Number(body.fontSize)||0,idealBibleFont(body.text))}return n}
function setPageCounter(slide,index,total){slide.elements=slide.elements.filter(e=>e.role!=='pageCounter');if(total>1)slide.elements.push(pageCounterElement(`(${toKm(index)}/${toKm(total)})`,project))}
function splitBibleSlide(slideIdToSplit,parts){if(!project)return;const index=project.slides.findIndex(s=>s.id===slideIdToSplit);if(index<0)return;const source=project.slides[index],rows=verseRowsFromSlide(source);parts=Math.max(2,Math.min(Number(parts)||2,3,rows.length));if(rows.length<2)return toast('Slide នេះមិនមានខគម្ពីរគ្រប់គ្រាន់សម្រាប់ចែកទេ');if(rows.length<parts)return toast(`មានតែ ${toKm(rows.length)} ខ — មិនអាចចែកជា ${toKm(parts)} slide បានទេ`);const groups=balancedVerseGroups(rows,parts),family=splitFamilyRange(index),hadFamily=family.end>family.start||!!counterElement(source);pushHistory();const pieces=groups.map(g=>cloneSlidePiece(source,g));project.slides.splice(index,1,...pieces);const added=pieces.length-1,newStart=family.start,newEnd=family.end+added,total=newEnd-newStart+1;for(let i=newStart;i<=newEnd;i++)setPageCounter(project.slides[i],i-newStart+1,total);slideId=pieces[0].id;elementId=null;hideSlideContextMenu();renderAll();scheduleSave();toast(`ចែកតាមខជា ${toKm(parts)} slide · (${toKm(1)}/${toKm(total)}) → (${toKm(total)}/${toKm(total)})`)}
function autoSplitParts(slide){const rows=verseRowsFromSlide(slide),chars=rows.reduce((n,r)=>n+r.line.length,0);return rows.length>=8||chars>760?3:2}
function ensureSlideContextMenu(){let m=$('#slideContextMenu');if(m)return m;m=document.createElement('div');m.id='slideContextMenu';m.className='slideContextMenu hidden';m.innerHTML=`<div class="ctxTitle">Slide actions</div><button data-ctx="duplicate">${hero('M15.75 17.25v3.375c0 .621-.504 1.125-1.125 1.125h-9.75A1.125 1.125 0 0 1 3.75 20.625V10.875c0-.621.504-1.125 1.125-1.125H8.25m7.5 7.5h3.375c.621 0 1.125-.504 1.125-1.125V6.375c0-.621-.504-1.125-1.125-1.125H9.375c-.621 0-1.125.504-1.125 1.125V9.75m7.5 7.5H9.375A1.125 1.125 0 0 1 8.25 16.125V9.75')}<span>Duplicate selected</span></button><button data-ctx="selectAll">${hero('M3.75 4.5h16.5v15H3.75z')}<span>Select all slides</span></button><button data-ctx="moveFirst"><span>Move selected to beginning</span></button><button data-ctx="moveLast"><span>Move selected to end</span></button><div class="ctxSep"></div><div class="ctxTitle">Bible split</div><button data-split="2"><span>ចែកតាមខ</span><b>2 slides</b></button><button data-split="3"><span>ចែកតាមខ</span><b>3 slides</b></button><button data-split="auto"><span>Auto split</span><b>Best fit</b></button><div class="ctxSep"></div><button data-ctx="delete" class="danger">${hero('m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673A2.25 2.25 0 0 1 15.916 21.75H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916')}<span>Delete selected</span></button>`;document.body.appendChild(m);m.onclick=e=>{const b=e.target.closest('button');if(!b)return;const id=m.dataset.slide;if(b.dataset.split){const sl=project?.slides.find(s=>s.id===id);splitBibleSlide(id,b.dataset.split==='auto'?autoSplitParts(sl):+b.dataset.split);return}hideSlideContextMenu();if(b.dataset.ctx==='duplicate')duplicateSelectedSlides();else if(b.dataset.ctx==='delete')deleteSelectedSlides();else if(b.dataset.ctx==='selectAll')selectAllSlides();else if(b.dataset.ctx==='moveFirst')moveSelectedToEdge('first');else if(b.dataset.ctx==='moveLast')moveSelectedToEdge('last')};return m}
function moveSelectedToEdge(where){const moving=selectedSlides();if(!moving.length)return;pushHistory();const ids=new Set(moving.map(s=>s.id)),rest=project.slides.filter(s=>!ids.has(s.id));project.slides=where==='first'?[...moving,...rest]:[...rest,...moving];slideId=moving[0].id;renderAll();scheduleSave()}
function showSlideContextMenu(x,y,id){if(!selectedSlideIds.has(id)){selectedSlideIds=new Set([id]);slideId=id;slideAnchorId=id;renderThumbs()}const sl=project?.slides.find(s=>s.id===id),rows=verseRowsFromSlide(sl),m=ensureSlideContextMenu();m.dataset.slide=id;m.querySelectorAll('[data-split]').forEach(b=>{const need=b.dataset.split==='3'?3:2;b.disabled=rows.length<need});m.classList.remove('hidden');const r=m.getBoundingClientRect(),pad=8;m.style.left=Math.max(pad,Math.min(x,innerWidth-r.width-pad))+'px';m.style.top=Math.max(pad,Math.min(y,innerHeight-r.height-pad))+'px'}
function hideSlideContextMenu(){$('#slideContextMenu')?.classList.add('hidden')}
async function smartSlides(input){
 const lines=input.replace(/\r/g,'').split('\n'),out=[],warn=[];let buf=[];
 const flush=()=>{const a=buf.map(x=>x.trim()).filter(Boolean);if(a.length){const title=a.length>1?a[0]:'',body=a.length>1?a.slice(1).join('\n'):a[0];out.push(textSlide(title,body));buf=[]}};
 for(const raw of lines){
  const line=raw.trim();if(!line){flush();continue}
  if(parseRef(line)){
   flush();
   try{
    const p=await passage(line),parts=splitPassageRows(p);
    parts.forEach((rows,i)=>{const part=parts.length>1?`(${toKm(i+1)}/${toKm(parts.length)})`:'';out.push(bibleSlide(p.reference,rows.join('\n'),part))})
   }catch(e){warn.push(e.message)}
   continue
  }
  if(/^ចំណងជើង\s*[:：]/.test(line)){flush();out.push(titleSlide(line.replace(/^ចំណងជើង\s*[:：]\s*/,'')));continue}
  if(/ព្រះបន្ទូល.*ម៉ោង/.test(line)){flush();out.push(titleSlide(line));continue}
  buf.push(line)
 }
 flush();return{slides:out,warn}
}
async function runSmart(replace){const input=$('#smartInput').value.trim();if(!input)return;$('#smartStatus').textContent='កំពុងស្វែងរក Bible1954...';try{const g=await smartSlides(input);if(!g.slides.length)throw Error('រកមិនឃើញ slide content');pushHistory();if(replace)project.slides=g.slides;else project.slides.push(...g.slides);slideId=(replace?project.slides[0]:g.slides[0]).id;elementId=null;$('#smartStatus').textContent=g.warn.length?g.warn.join(' · '):`បានបង្កើត ${g.slides.length} slides`;renderAll();scheduleSave();closeDlg('smartDlg');toast(`Generated ${g.slides.length} slides`)}catch(e){$('#smartStatus').textContent=e.message}}
async function repairLegacyRefs(){if(!project)return;const replacements=[];let changed=0;pushHistory();for(const s of project.slides){const lines=s.elements.filter(e=>['text','bible'].includes(e.type)).sort((a,b)=>(a.y||0)-(b.y||0)).flatMap(e=>String(e.text||'').split(/\n+/).map(x=>x.trim()).filter(Boolean));if(lines.length&&lines.every(x=>parseRef(x))){const generated=[];let ok=true;for(const line of lines){try{const p=await passage(line),parts=splitPassageRows(p);parts.forEach((rows,i)=>{const ref=parts.length>1?`${p.reference} (${toKm(i+1)}/${toKm(parts.length)})`:p.reference;generated.push(bibleSlide(ref,rows.join('\n')))})}catch{ok=false;break}}if(ok&&generated.length){replacements.push(...generated);changed++;continue}}replacements.push(s)}if(!changed){historyStack.pop();updateUndoUI();$('#smartStatus').textContent='មិនមាន slide ចាស់ដែលត្រូវជួសជុលទេ';return}project.slides=replacements;slideId=project.slides[0]?.id||null;elementId=null;renderAll();scheduleSave();$('#smartStatus').textContent=`បានជួសជុល ${changed} slide និងបម្លែងលេខយោងទៅ Bible1954`;toast(`Repaired ${changed} slide${changed>1?'s':''}`)}
/* design */
function renderDesign(){fillFontSelect($('#designTitleFont'),project.master.titleFont);fillFontSelect($('#designBodyFont'),project.master.bodyFont);$('#designTheme').value=project.master.theme;$('#designRatio').value=project.ratio;$('#designBg').value=project.master.bg;$('#designBgText').value=project.master.bg;$('#designAccent').value=project.master.accent;$('#designAccentText').value=project.master.accent;$('#designFontPreview').innerHTML=fonts.map(f=>`<button class="fontOption ${[project.master.titleFont,project.master.bodyFont].includes(f.id)?'active':''}" data-preview-font="${esc(f.id)}"><span class="fn">${esc(f.name)}</span><span class="fp" style="font-family:${f.css}">ព្រះបន្ទូលនៃព្រះអម្ចាស់</span></button>`).join('');updateGlobalButtons()}
function applyDesign(){pushHistory();const theme=$('#designTheme').value,t=THEMES[theme];project.ratio=$('#designRatio').value;project.master.theme=theme;project.master.bg=$('#designBgText').value||t.bg;project.master.accent=$('#designAccentText').value||t.accent;project.master.fg=t.fg;project.master.titleFont=$('#designTitleFont').value;project.master.bodyFont=$('#designBodyFont').value;for(const s of project.slides)for(const e of s.elements){if(e.type==='text'&&e.bold)e.fontFamily=project.master.titleFont;else if(['text','bible'].includes(e.type))e.fontFamily=project.master.bodyFont;if(['text','bible'].includes(e.type)&&(!e.color||['#fff','#ffffff','#f8fbf9','#17231c'].includes(e.color.toLowerCase())))e.color=project.master.fg}renderAll();scheduleSave();closeDlg('designDlg')}
/* presenter */
function presentRole(e,s,index){if(e.role)return e.role;if(e.type==='bible')return'bible';if(['Title','Section'].includes(s.name))return'title';if(s.name==='Bible'){const texts=s.elements.filter(x=>x.type==='text');if(e.id===texts[0]?.id)return'bibleRef';if(e.id===texts[1]?.id)return'bibleText'}if(s.name==='Text'&&index===0&&s.elements.length>1)return'subtitle';return'body'}
function roleFontRange(role,stageW){const k=stageW/1920;const map={title:[72,128],subtitle:[42,74],bibleRef:[38,60],bibleText:[58,96],bible:[56,90],body:[50,82]};const [min,max]=map[role]||map.body;return[Math.max(22,min*k),Math.max(30,max*k)]}
function fitPresentNode(node,e,role){if(!['text','bible'].includes(e.type))return;const stage=$('#presentCanvas'),range=roleFontRange(role,stage.clientWidth),min=range[0]*presentTextScale,max=range[1]*presentTextScale;const authored=Math.max(1,+e.fontSize||36)*stage.clientWidth/960*presentTextScale;let hi=Math.max(min,Math.min(max,Math.max(authored,min))),lo=Math.min(min,hi);node.style.fontSize=hi+'px';const fits=()=>node.scrollHeight<=node.clientHeight+2&&node.scrollWidth<=node.clientWidth+2;if(fits())return;for(let i=0;i<12;i++){const mid=(lo+hi)/2;node.style.fontSize=mid+'px';if(fits())lo=mid;else hi=mid}node.style.fontSize=Math.max(18,lo)+'px'}
function showPresentControls(){const p=$('#presenter');p.classList.add('controlsVisible');clearTimeout(presentControlsTimer);presentControlsTimer=setTimeout(()=>p.classList.remove('controlsVisible'),2600)}
function setPresentScale(v){presentTextScale=Math.max(.7,Math.min(1.5,Math.round(v*20)/20));$('#presentScaleLabel').textContent=Math.round(presentTextScale*100)+'%';renderPresent();showPresentControls()}
function renderPresent(){const s=project.slides[presentIndex],stage=$('#presentCanvas'),theme=slideTheme();stage.classList.toggle('ratio43',project.ratio==='4:3');stage.style.background=theme.bg;stage.style.setProperty('--verse-number-color',verseNumberColor(theme.bg));stage.innerHTML=s.elements.sort((a,b)=>(a.z||1)-(b.z||1)).map(e=>`<div class="presentEl" data-present-id="${e.id}" data-type="${e.type}"><div class="content">${elementInner(e)}</div></div>`).join('');stage.querySelectorAll('.presentEl').forEach(n=>{const e=s.elements.find(x=>x.id===n.dataset.presentId);applyElStyle(n,e,stage);fitElementToBox(n,e,stage);if(presentTextScale!==1){const c=n.querySelector('.content'),px=parseFloat(c.style.fontSize)||0;c.style.fontSize=(px*presentTextScale)+'px'}});$('#presentCounter').textContent=`${presentIndex+1} / ${project.slides.length}`;$('#presentBlack').classList.toggle('hidden',!presentBlack)}
function startPresent(){if(!project)return;presentIndex=Math.max(0,project.slides.findIndex(s=>s.id===slideId));presentBlack=false;presentTextScale=1;presentFsStarted=false;$('#presentScaleLabel').textContent='100%';const presenter=$('#presenter');presenter.classList.remove('hidden');renderPresent();showPresentControls();const req=presenter.requestFullscreen?.({navigationUI:'hide'})||presenter.requestFullscreen?.();if(req?.then)req.then(()=>presentFsStarted=true).catch(()=>{})}
function stopPresent(){presentFsStarted=false;$('#presenter').classList.add('hidden');if(document.fullscreenElement)document.exitFullscreen?.().catch(()=>{})}
function stepPresent(d){presentIndex=Math.max(0,Math.min(project.slides.length-1,presentIndex+d));renderPresent()}
/* pptx */
function cssHex(v,fallback='FFFFFF'){if(!v)return fallback;const s=String(v).trim();if(/^#[0-9a-f]{6}$/i.test(s))return s.slice(1);const m=s.match(/rgba?\((\d+)[, ]+(\d+)[, ]+(\d+)/i);return m?[+m[1],+m[2],+m[3]].map(n=>n.toString(16).padStart(2,'0')).join('').toUpperCase():fallback}
function pptxRichRuns(e,theme){if(!e.rich)return null;const root=document.createElement('div');root.innerHTML=sanitizeRichHTML(e.rich);const runs=[],base={color:(e.color||project.master.fg||theme.fg).replace('#',''),fontFace:fontBy(e.fontFamily).family,bold:!!e.bold,italic:!!e.italic},numColor=verseNumberColor(theme.bg).replace('#',''),sup=project.master.verseNumberStyle==='superscript';const walk=(n,opt={...base})=>{if(n.nodeType===3){if(n.nodeValue)runs.push({text:n.nodeValue,options:{...opt}});return}if(n.nodeType!==1)return;const o={...opt},tag=n.tagName;if(['B','STRONG'].includes(tag))o.bold=true;if(['I','EM'].includes(tag))o.italic=true;if(tag==='U')o.underline={color:o.color};if(tag==='FONT'){if(n.getAttribute('face'))o.fontFace=n.getAttribute('face');if(n.getAttribute('color'))o.color=cssHex(n.getAttribute('color'),o.color)}const st=n.style;if(st?.color)o.color=cssHex(st.color,o.color);if(st?.fontFamily)o.fontFace=st.fontFamily.replace(/["']/g,'').split(',')[0];if(st?.fontWeight&&(+st.fontWeight>=600||st.fontWeight==='bold'))o.bold=true;if(st?.fontStyle==='italic')o.italic=true;if(st?.backgroundColor)o.highlight=cssHex(st.backgroundColor,'FFE066');if(n.classList?.contains('verseNo')){o.bold=true;o.color=numColor;o.superscript=sup}if(tag==='BR'){runs.push({text:'',options:{...o,breakLine:true}});return}for(const c of n.childNodes)walk(c,o);if(['DIV','P'].includes(tag))runs.push({text:'',options:{...o,breakLine:true}})};for(const n of root.childNodes)walk(n);return runs}
function pptxBibleRuns(e,theme){const runs=[],bodyColor=(e.color||project.master.fg||theme.fg).replace('#',''),numColor=verseNumberColor(theme.bg).replace('#',''),sup=project.master.verseNumberStyle==='superscript';if(e.type==='bible'&&e.ref)runs.push({text:e.ref,options:{bold:true,color:(project.master.accent||theme.accent).replace('#',''),breakLine:true}});const lines=String(e.text||'').split(/\n+/).filter(Boolean);for(const line of lines){const m=line.match(/^\s*([០-៩0-9]+)\s+(.*)$/);if(m){runs.push({text:m[1],options:{bold:true,color:numColor,superscript:sup}});runs.push({text:' '+m[2],options:{color:bodyColor,breakLine:true}})}else runs.push({text:line,options:{color:bodyColor,breakLine:true}})}return runs}
function loadScript(src){return new Promise((res,rej)=>{if(window.PptxGenJS)return res();const s=document.createElement('script');s.src=src;s.onload=res;s.onerror=rej;document.head.append(s)})}
async function exportPptx(){if(!project)return;const btn=$('#exportBtn'),old=btn.textContent;btn.disabled=true;btn.textContent='Exporting…';try{if(!window.PptxGenJS)await loadScript('https://cdn.jsdelivr.net/gh/gitbrent/pptxgenjs@3.12.0/dist/pptxgen.bundle.js');const pptx=new PptxGenJS();pptx.layout=project.ratio==='4:3'?'LAYOUT_4X3':'LAYOUT_WIDE';pptx.author='Powerslide · Bible1954';pptx.title=project.title;const W=project.ratio==='4:3'?10:13.333,H=7.5,theme=slideTheme();for(const s of project.slides){const sl=pptx.addSlide();sl.background={color:(project.master.bg||theme.bg).replace('#','')};for(const e of s.elements.sort((a,b)=>(a.z||1)-(b.z||1))){const x=e.x/100*W,y=e.y/100*H,w=e.w/100*W,h=e.h/100*H;if(e.type==='shape'){sl.addShape(pptx.ShapeType.rect,{x,y,w,h,fill:{color:(e.fill||project.master.accent).replace('#',''),transparency:Math.round((1-(e.opacity??1))*100)},line:{color:(e.fill||project.master.accent).replace('#',''),transparency:100},radius:e.radius||0})}else if(e.type==='image'&&e.data){sl.addImage({data:e.data,x,y,w,h})}else{const isBible=e.type==='bible'||e.role==='bibleText',text=e.rich?(pptxRichRuns(e,theme)||e.text):(isBible?pptxBibleRuns(e,theme):(e.text||''));sl.addText(text,{x,y,w,h,fontFace:fontBy(e.fontFamily).family,fontSize:Math.max(8,(e.fontSize||32)*.75),bold:!!e.bold,italic:!!e.italic,color:(e.color||project.master.fg).replace('#',''),align:e.align||'left',valign:e.valign==='top'?'top':e.valign==='bottom'?'bottom':'mid',margin:0.02,breakLine:false,fit:'shrink',transparency:Math.round((1-(e.opacity??1))*100)})}}}await pptx.writeFile({fileName:`${project.date}-${project.title.replace(/[\\/:*?"<>|]/g,'-')}.pptx`});toast('PPTX រួចរាល់')}catch(e){console.error(e);alert('PPTX export ត្រូវការ Internet លើកដំបូងសម្រាប់ PPTX engine។ Browser presentation នៅតែប្រើ offline បាន។')}finally{btn.disabled=false;btn.textContent=old}}
/* resizable slide thumbnail rail */
function applyRailWidth(w,save=true){railWidth=Math.max(160,Math.min(430,Number(w)||220));document.documentElement.style.setProperty('--rail-w',railWidth+'px');if(save)localStorage.setItem('powerslide.railWidth',String(Math.round(railWidth)))}
function scheduleRailPreview(){cancelAnimationFrame(railRenderRAF);railRenderRAF=requestAnimationFrame(()=>{if(project){renderThumbs();renderCanvas()}})}
function beginRailResize(ev){if(innerWidth<=900)return;railResize={startX:ev.clientX,startW:railWidth};document.body.classList.add('resizingRail');ev.currentTarget.setPointerCapture?.(ev.pointerId);ev.preventDefault()}
function moveRailResize(ev){if(!railResize)return;applyRailWidth(railResize.startW+(ev.clientX-railResize.startX),false);scheduleRailPreview()}
function endRailResize(){if(!railResize)return;railResize=null;document.body.classList.remove('resizingRail');applyRailWidth(railWidth,true);scheduleRailPreview()}
/* events */
function bindDialogs(){$$('[data-close]').forEach(b=>b.onclick=()=>closeDlg(b.dataset.close))}
function bindEvents(){
 applyLibrarySidebarWidth();$('#backBible').onclick=$('#libBackBible').onclick=()=>{if(window.parent!==window)window.parent.postMessage({type:'tahoe-app-command',app:'powerslide',command:'open',target:'bible'},'*');else location.href='../bible/index.html'};$('#rightUndoBtn').onclick=undo;$('#rightRedoBtn').onclick=redo;$('#rightPresentBtn').onclick=startPresent;$('#rightExportBtn').onclick=exportPptx;$('#rightFullscreenBtn').onclick=()=>{if(window.parent!==window)window.parent.postMessage({type:'tahoe-app-command',app:'powerslide',command:'fullscreen'},'*')};$('#mobileUndoBtn').onclick=undo;$('#mobileRedoBtn').onclick=redo;$('#mobilePresentBtn').onclick=startPresent;$('#mobileExportBtn').onclick=exportPptx;$('#mobileFullscreenBtn').onclick=()=>{if(window.parent!==window)window.parent.postMessage({type:'tahoe-app-command',app:'powerslide',command:'fullscreen'},'*');else document.documentElement.requestFullscreen?.()};$('#mobileExitBtn').onclick=()=>{if(window.parent!==window)window.parent.postMessage({type:'tahoe-app-command',app:'powerslide',command:'close'},'*');else location.href='../../index.html'};$('#openFinderProjectsBtn').onclick=()=>finderRequest('open-folder');$('#gateLogin').onclick=powerslideGoogleLogin;$('#openLibrary').onclick=showLibrary;$('#projectInfoBtn').onclick=()=>{if(!project)return;$('#infoTitle').value=project.title;$('#infoDate').value=project.date;$('#infoService').value=project.service||'';openDlg('projectInfoDlg')};$('#saveProjectInfo').onclick=()=>{if(!project)return;pushHistory();project.title=$('#infoTitle').value.trim()||project.title;project.date=$('#infoDate').value||project.date;project.service=$('#infoService').value.trim();renderAll();scheduleSave();closeDlg('projectInfoDlg')};$('#undoBtn').onclick=undo;$('#redoBtn').onclick=redo;$('#presentBtn').onclick=startPresent;$('#exportBtn').onclick=exportPptx;
 $('#mobileSlides').onclick=()=>{if(innerWidth<=900){scrollActiveThumbIntoView('smooth');$('#slideList')?.scrollIntoView({behavior:'smooth',block:'nearest'})}else $('#rail').classList.toggle('mobileOpen')};
 $('#closeRail').onclick=()=>{if(innerWidth<=900)$('#rail').classList.remove('mobileOpen');else{editorSidebarHidden=true;localStorage.setItem("powerslide.editorSidebarHidden","1");applyEditorSidebarState()}};
 const psEditorSidebarToggle=$("#psEditorSidebarToggle");if(psEditorSidebarToggle)psEditorSidebarToggle.onclick=toggleEditorSidebar;
 $('#mobileProps').onclick=()=>{if(innerWidth<=900){$('#editorView').classList.toggle('mobilePropsCollapsed')}else $('#inspector').classList.toggle('mobileOpen')};
 $('#closeInspector').onclick=()=>{if(innerWidth<=900)$('#editorView').classList.add('mobilePropsCollapsed');else $('#inspector').classList.remove('mobileOpen')};
 const rr=$('#railResizer');if(rr)rr.onpointerdown=beginRailResize;window.addEventListener('pointermove',moveRailResize);window.addEventListener('pointerup',endRailResize);
 $('#addSlideBtn').onclick=()=>addSlide();$('#duplicateSlideBtn').onclick=duplicateSelectedSlides;$('#deleteSlideBtn').onclick=deleteSelectedSlides;$('#addTextBtn').onclick=addText;$('#addShapeBtn').onclick=addShape;$('#addImageBtn').onclick=()=>$('#imageFile').click();$('#imageFile').onchange=e=>{addImageFile(e.target.files[0]);e.target.value=''};
 $('#addBibleBtn').onclick=()=>{openDlg('bibleDlg');$('#bibleRefInput').focus()};$('#insertBibleBtn').onclick=async()=>{if(await addBible($('#bibleRefInput').value.trim()))closeDlg('bibleDlg')};$('#bibleRefInput').oninput=async()=>{const q=$('#bibleRefInput').value.trim();if(!q)return;try{const p=await passage(q);$('#biblePreview').textContent=p.reference+' — '+p.text.slice(0,180)+(p.text.length>180?'…':'')}catch{$('#biblePreview').textContent='មិនទាន់ស្គាល់លេខយោង'}};
 $('#smartBtn').onclick=()=>{openDlg('smartDlg');if(!$('#smartInput').value)$('#smartInput').value=localStorage.getItem('powerslide.smart')||''};$('#smartSample').onclick=()=>{$('#smartInput').value=SAMPLE};$('#smartInput').oninput=()=>localStorage.setItem('powerslide.smart',$('#smartInput').value);$('#smartRepair').onclick=repairLegacyRefs;$('#smartReplace').onclick=()=>runSmart(true);$('#smartAppend').onclick=()=>runSmart(false);
 $('#designBtn').onclick=()=>{renderDesign();openDlg('designDlg')};$('#verseStyleBtn').onclick=toggleVerseStyle;$('#designVerseStyleBtn').onclick=toggleVerseStyle;$('#applyFontAllBtn').onclick=()=>applyFontToAll($('#designBodyFont').value);$('#designTheme').onchange=()=>{const t=THEMES[$('#designTheme').value];$('#designBg').value=t.bg;$('#designBgText').value=t.bg;$('#designAccent').value=t.accent;$('#designAccentText').value=t.accent};$('#designBg').oninput=e=>$('#designBgText').value=e.target.value;$('#designAccent').oninput=e=>$('#designAccentText').value=e.target.value;$('#applyDesignBtn').onclick=applyDesign;$('#gridBtn').onclick=()=>{gridOn=!gridOn;renderCanvas()};
 $('#slideList').onclick=e=>{const x=e.target.closest('[data-slide]');if(!x)return;hideSlideContextMenu();setSelectionScope('slides');const id=x.dataset.slide;if(e.shiftKey)rangeSelectSlides(id);else if(e.metaKey||e.ctrlKey)toggleSlideSelection(id);else selectOnlySlide(id);$('#rail').classList.remove('mobileOpen')};$('#slideList').oncontextmenu=e=>{const x=e.target.closest('[data-slide]');if(!x)return;e.preventDefault();e.stopPropagation();setSelectionScope('slides');if(!selectedSlideIds.has(x.dataset.slide))selectOnlySlide(x.dataset.slide,{scroll:false});showSlideContextMenu(e.clientX,e.clientY,x.dataset.slide)};$('#slideList').ondragstart=e=>{const row=e.target.closest('[data-slide]');if(!row)return;const id=row.dataset.slide;if(!selectedSlideIds.has(id)){selectedSlideIds=new Set([id]);slideId=id;slideAnchorId=id}thumbDrag={ids:[...selectedSlideIds]};e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',id)};$('#slideList').ondragover=e=>{const row=e.target.closest('[data-slide]');if(!row||!thumbDrag)return;e.preventDefault();row.classList.add('dropTarget')};$('#slideList').ondragleave=e=>e.target.closest('[data-slide]')?.classList.remove('dropTarget');$('#slideList').ondrop=e=>{const row=e.target.closest('[data-slide]');if(!row||!thumbDrag)return;e.preventDefault();const r=row.getBoundingClientRect(),after=e.clientY>r.top+r.height/2;$$('.thumbRow.dropTarget').forEach(n=>n.classList.remove('dropTarget'));reorderSelectedSlides(row.dataset.slide,after);thumbDrag=null};$('#slideList').ondragend=()=>{thumbDrag=null;$$('.thumbRow.dropTarget').forEach(n=>n.classList.remove('dropTarget'))};$('#slideCanvas').onpointerdown=e=>{setSelectionScope('canvas');if(e.target.closest('[contenteditable="true"]'))return;const n=e.target.closest('.slide-element');if(n)beginDrag(e,n);else{elementId=null;selectedElementIds.clear();renderCanvas();renderInspector()}};window.addEventListener('pointermove',moveDrag);window.addEventListener('pointerup',endDrag);
 $('#projectTitle').oninput=e=>{project.title=e.target.value;scheduleSave()};
 $('#newProjectBtn').onclick=()=>{$('#newDate').value=nextSunday();openDlg('newProjectDlg')};$('#createProjectBtn').onclick=newProject;$('#projectSearch').oninput=renderLibrary;$('#importProjectBtn').onclick=()=>$('#importProjectFile').click();$('#importProjectFile').onchange=e=>{importProject(e.target.files[0]);e.target.value=''};
 $('#projectGroups').onclick=e=>{const a=e.target.closest('[data-act]'),wrap=e.target.closest('[data-project]');if(a&&wrap){const p=projects.find(x=>x.id===wrap.dataset.project);if(!p)return;if(a.dataset.act==='open')openProject(p.id);else if(a.dataset.act==='copy')duplicateProject(p);else if(a.dataset.act==='json')exportProject(p);else if(a.dataset.act==='rename'){const name=prompt('Presentation name',p.title);if(name?.trim()){p.title=name.trim();p.updatedAt=Date.now();idbPut(p);mirrorProjectToFinder(p,50);if(project?.id===p.id)project.title=p.title;renderLibrary();saveCloudCopy(p)}}else if(a.dataset.act==='delete'&&confirm('Delete project?'))deleteProject(p.id);return}const row=e.target.closest('[data-project-select]');if(row){libraryProjectId=row.dataset.project;renderLibrary();if(e.detail===2)openProject(libraryProjectId)}};
 $('#presentSmaller').onclick=e=>{e.stopPropagation();setPresentScale(presentTextScale-.1)};$('#presentBigger').onclick=e=>{e.stopPropagation();setPresentScale(presentTextScale+.1)};$('#presentReset').onclick=e=>{e.stopPropagation();setPresentScale(1)};$('#presentControls').onclick=e=>e.stopPropagation();$('#presenter').onmousemove=showPresentControls;$('#presenter').ontouchstart=showPresentControls;$('#presenter').onclick=e=>{if(e.target.id==='presenter'||e.target.id==='presentCanvas')stepPresent(1)};
 window.addEventListener('keydown',e=>{if(!$('#presenter').classList.contains('hidden')){if(['ArrowRight','PageDown',' '].includes(e.key))stepPresent(1);else if(['ArrowLeft','PageUp'].includes(e.key))stepPresent(-1);else if(e.key==='Escape')stopPresent();else if(e.key.toLowerCase()==='b'){presentBlack=!presentBlack;renderPresent()}else if(['+','='].includes(e.key))setPresentScale(presentTextScale+.1);else if(['-','_'].includes(e.key))setPresentScale(presentTextScale-.1);else if(e.key==='0')setPresentScale(1);e.preventDefault();return}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='s'){e.preventDefault();exportPptx();return}if(e.target.matches('input,textarea,select,[contenteditable="true"]'))return;if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();return}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='a'&&project){e.preventDefault();if(selectionScope==='slides')selectAllSlides();else{selectedElementIds=new Set(currentSlide().elements.map(x=>x.id));elementId=currentSlide().elements[0]?.id||null;renderCanvas();renderInspector();toast(`${selectedElementIds.size} objects selected`)}return}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='b'&&project){e.preventDefault();applyTextFormat('bold');return}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='d'&&project){e.preventDefault();selectionScope==='slides'?duplicateSelectedSlides():(currentEl()?layerAction('duplicate'):duplicateSlide());return}if(e.key==='F2'||e.key==='Enter'&&currentEl()){if(currentEl()&&isTextElement(currentEl())){e.preventDefault();startInlineEdit(currentEl().id)}return}if(project&&['ArrowRight','ArrowDown'].includes(e.key)){e.preventDefault();stepEditor(1);return}if(project&&['ArrowLeft','ArrowUp'].includes(e.key)){e.preventDefault();stepEditor(-1);return}if(project&&e.key==='Home'){e.preventDefault();edgeEditor('home');return}if(project&&e.key==='End'){e.preventDefault();edgeEditor('end');return}if(e.key==='Delete'||e.key==='Backspace'){if(selectionScope==='slides'&&selectedSlideIds.size){e.preventDefault();deleteSelectedSlides()}else if(currentEl()){e.preventDefault();layerAction('delete')}}});
 document.addEventListener('selectionchange',rememberTextRange);document.addEventListener('fullscreenchange' ,()=>{if(presentFsStarted&&!document.fullscreenElement&&!$('#presenter').classList.contains('hidden')){presentFsStarted=false;$('#presenter').classList.add('hidden')}});window.addEventListener('resize',()=>{if(project){renderCanvas();if(!$('#presenter').classList.contains('hidden'))renderPresent()}});bindDialogs()
}
/* init */
window.addEventListener('pointerdown',e=>{if(!e.target.closest('#slideContextMenu'))hideSlideContextMenu()},{capture:true});window.addEventListener('blur',hideSlideContextMenu);window.addEventListener('resize',hideSlideContextMenu);window.addEventListener('scroll',hideSlideContextMenu,true);
async function init(){applyRailWidth(railWidth,false);applyProjectSidebarWidth();applyProjectSidebarState();applyEditorSidebarState();await Promise.all([openDB(),loadFonts(),loadBible()]);projects=(await idbAll()).map(normalizeProject);if(window.parent!==window)await mergeFinderProjects();bindEvents();await initFirebase();renderLibrary();notifyTahoeProjectState('library');$('#newDate').value=nextSunday();if(window.parent===window&&'serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('sw.js?v=60').catch(()=>{});const id=new URLSearchParams(location.search).get('project');if(id&&projects.some(p=>p.id===id))openProject(id)}
console.info('Powerslide Professional v7');
init().catch(e=>{console.error(e);document.body.innerHTML=`<div style="padding:30px;color:white;font-family:sans-serif">Powerslide could not start.<br><br>${esc(e.message)}<br><br>Use localhost or HTTPS.</div>`})
})();
