/* Tahoe v74 · AllSong Next
   Admin Dashboard shell + shared worship-song library + PowerSlide bridge. */
(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const WIN=$('#allSongNextWindow'),launcher=$('#allSongNextLauncher');if(!WIN||!launcher)return;
const LS='tahoe.allsong.next.v74',KM='០១២៣៤៥៦៧៨៩';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const saved=(()=>{try{return JSON.parse(localStorage.getItem(LS)||'{}')}catch{return{}}})();
const st={songs:[],byId:new Map(),loaded:false,query:'',view:saved.view||'all',selected:saved.selected||null,favorites:new Set(saved.favorites||[]),recent:saved.recent||[],queue:new Set(),sidebar:Number(saved.sidebar)||292,sidebarOpen:saved.sidebarOpen!==false,window:saved.window||null,zoomed:false,preZoom:null,cloudUpdated:Number(saved.cloudUpdated)||0,saveTimer:null};
function profile(){return window.TahoeAdmin?.state?.().profile||{}}
function canOpen(){try{return typeof canUseDesktopApps==='function'?canUseDesktopApps():false}catch{return false}}
function updateAccess(){launcher.style.display=canOpen()?'grid':'none';if(!canOpen())close()}
function persist(localOnly=false){const data={view:st.view,selected:st.selected,favorites:[...st.favorites],recent:st.recent.slice(0,80),sidebar:st.sidebar,sidebarOpen:st.sidebarOpen,window:st.window,cloudUpdated:Date.now()};st.cloudUpdated=data.cloudUpdated;try{localStorage.setItem(LS,JSON.stringify(data))}catch{}if(!localOnly){clearTimeout(st.saveTimer);st.saveTimer=setTimeout(()=>window.TahoeFirebase?.writeOwnAllSongState?.(data).catch(()=>{}),500)}}
function applyCloudState(v){if(!v||typeof v!=='object')return;if(Number(v.updatedAt||v.cloudUpdated||0)<st.cloudUpdated)return;st.favorites=new Set(Array.isArray(v.favorites)?v.favorites:[]);st.recent=Array.isArray(v.recent)?v.recent:[];if(v.view)st.view=v.view;if(v.selected)st.selected=v.selected;st.cloudUpdated=Number(v.updatedAt||v.cloudUpdated)||Date.now();render()}
function toast(msg){const el=$('#asnToast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),1800)}
function normalize(s){return String(s||'').normalize('NFKC').toLowerCase().replace(/[\u200b\u200c\u200d]/g,'').replace(/[០-៩]/g,d=>KM.indexOf(d)).replace(/[\s\-–—_.:,;!?។៕()\[\]{}"'“”‘’/\\]+/g,'')}
async function load(){if(st.loaded)return;const j=await fetch('data/songs/songs.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Song library unavailable');return r.json()});st.songs=j.songs||[];st.byId=new Map(st.songs.map(x=>[x.id,x]));st.loaded=true;if(!st.selected)st.selected=st.songs[0]?.id||null;render()}
function filtered(){let rows=st.songs;if(st.view==='favorites')rows=rows.filter(s=>st.favorites.has(s.id));else if(st.view==='recent'){const map=new Map(st.songs.map(s=>[s.id,s]));rows=st.recent.map(id=>map.get(id)).filter(Boolean)}const q=normalize(st.query);if(q)rows=rows.filter(s=>[s.title,...(s.aliases||[])].some(a=>normalize(a).includes(q))||normalize(s.lyrics).includes(q));return rows}
function select(id){if(!st.byId.has(id))return;st.selected=id;st.recent=[id,...st.recent.filter(x=>x!==id)].slice(0,80);persist();render()}
function toggleFav(id){st.favorites.has(id)?st.favorites.delete(id):st.favorites.add(id);persist();render()}
function toggleQueue(id){st.queue.has(id)?st.queue.delete(id):st.queue.add(id);render()}
function updateProfile(){const p=profile(),a=$('#asnAvatar'),n=$('#asnAccountName'),s=$('#asnAccountSubtitle');if(n)n.textContent=p.displayName||p.email?.split('@')[0]||'User';if(s)s.textContent=p.subtitle||'Account';if(a)a.innerHTML=p.photoURL?`<img src="${esc(p.photoURL)}" alt="">`:esc((p.displayName||p.email||'U').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase())}
function renderSidebar(rows){$$('.asn-nav-item',WIN).forEach(b=>b.classList.toggle('active',b.dataset.view===st.view));const counts={all:st.songs.length,favorites:st.favorites.size,recent:st.recent.length};Object.entries(counts).forEach(([k,v])=>{const e=$(`#asnCount-${k}`);if(e)e.textContent=v});const box=$('#asnSidebarList');if(!box)return;box.innerHTML=rows.slice(0,80).map(s=>`<button class="asn-song-mini${s.id===st.selected?' active':''}" data-song="${s.id}"><strong>${esc(s.title)}</strong><small>${(s.lyrics.match(/\n/g)||[]).length+1} lyric lines</small></button>`).join('')||`<div class="asn-empty">No songs found</div>`}
function render(){if(!st.loaded)return;const rows=filtered(),sel=st.byId.get(st.selected)||rows[0]||null;if(sel&&sel.id!==st.selected)st.selected=sel.id;renderSidebar(rows);const cards=$('#asnCards'),meta=$('#asnLibraryMeta');if(meta)meta.textContent=`${rows.length} songs`;if(cards)cards.innerHTML=rows.map(s=>`<div class="asn-card${s.id===st.selected?' active':''}" data-song="${s.id}"><div><div class="asn-card-title">${esc(s.title)}</div><div class="asn-card-meta">${(s.sources||[]).join(' + ')} · ${(s.lyrics.match(/\n/g)||[]).length+1} lines</div></div><div class="asn-card-actions"><button class="asn-mini-btn fav${st.favorites.has(s.id)?' on':''}" data-fav="${s.id}" title="Favorite"><i class="${st.favorites.has(s.id)?'ri-star-fill':'ri-star-line'}"></i></button><button class="asn-mini-btn${st.queue.has(s.id)?' active':''}" data-queue="${s.id}" title="Add to worship queue"><i class="ri-add-circle-line"></i></button></div></div>`).join('')||`<div class="asn-empty">No songs found</div>`;const title=$('#asnDetailTitle'),sub=$('#asnDetailMeta'),lyrics=$('#asnLyrics'),fav=$('#asnFavoriteBtn');if(sel){title.textContent=sel.title;sub.textContent=`${(sel.sources||[]).join(' + ')} · ${sel.id}`;lyrics.textContent=sel.lyrics;fav.innerHTML=`<i class="${st.favorites.has(sel.id)?'ri-star-fill':'ri-star-line'}"></i><span>${st.favorites.has(sel.id)?'Favorited':'Favorite'}</span>`;fav.classList.toggle('active',st.favorites.has(sel.id))}else{title.textContent='AllSong';sub.textContent='';lyrics.textContent='Choose a song.'}const q=$('#asnQueueBtn');if(q)q.innerHTML=`<i class="ri-play-list-add-line"></i><span>Queue ${st.queue.size||''}</span>`;updateProfile()}
function sendToPowerSlide(ids){const list=(ids?.length?ids:[st.selected]).filter(Boolean);if(!list.length)return;const api=window.TahoePowerSlideNext;if(!api?.generateSongs)return toast('PowerSlide update is still loading');api.generateSongs(list,{open:true,append:true});toast(`${list.length} song${list.length>1?'s':''} sent to PowerSlide`)}
function open(){if(!canOpen())return window.TahoeAdmin?.toast?.('Pro access required');restoreWindow();WIN.classList.add('open');launcher.classList.add('active');updateProfile();load().catch(e=>toast(e.message));focus();const remote=window.TahoeFirebase?.readOwnAllSongState?.();if(remote?.then)remote.then(applyCloudState).catch(()=>{})}
function close(){WIN.classList.remove('open');launcher.classList.remove('active')}
function focus(){try{focusTahoeWindow(WIN)}catch{}}
function restoreWindow(){if(st.window&&innerWidth>760)Object.assign(WIN.style,st.window);WIN.style.setProperty('--asn-sidebar',st.sidebar+'px');WIN.classList.toggle('sidebar-hidden',!st.sidebarOpen);responsive()}
function saveWindow(){if(innerWidth<=760)return;const r=WIN.getBoundingClientRect();st.window={left:r.left+'px',top:r.top+'px',width:r.width+'px',height:r.height+'px',transform:'none'};persist(true)}
function toggleZoom(){if(innerWidth<=760)return;if(st.zoomed){st.zoomed=false;if(st.preZoom)Object.assign(WIN.style,st.preZoom)}else{const r=WIN.getBoundingClientRect();st.preZoom={left:r.left+'px',top:r.top+'px',width:r.width+'px',height:r.height+'px',transform:'none'};st.zoomed=true;Object.assign(WIN.style,{left:'1vw',top:'1vh',width:'98vw',height:'98vh',transform:'none'})}saveWindow();responsive()}
function responsive(){const w=WIN.getBoundingClientRect().width;WIN.classList.toggle('compact',w<900)}
function bindMotion(){let drag=null,resize=null;$$('[data-asn-drag],.asn-drag-edge',WIN).forEach(h=>{h.addEventListener('pointerdown',e=>{if(innerWidth<=760||e.target.closest('button,input,select,textarea,[data-no-drag]'))return;e.preventDefault();const r=WIN.getBoundingClientRect();drag={id:e.pointerId,x:e.clientX,y:e.clientY,left:r.left,top:r.top,w:r.width,h:r.height};h.setPointerCapture(e.pointerId);WIN.classList.add('dragging');focus()});h.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const l=clamp(drag.left+e.clientX-drag.x,0,innerWidth-drag.w),t=clamp(drag.top+e.clientY-drag.y,0,innerHeight-drag.h);Object.assign(WIN.style,{left:l+'px',top:t+'px',transform:'none'})});const end=e=>{if(!drag||drag.id!==e.pointerId)return;drag=null;WIN.classList.remove('dragging');saveWindow()};h.addEventListener('pointerup',end);h.addEventListener('pointercancel',end)});$$('[data-asn-resize]',WIN).forEach(h=>{h.addEventListener('pointerdown',e=>{if(innerWidth<=760)return;e.preventDefault();e.stopPropagation();const r=WIN.getBoundingClientRect();resize={id:e.pointerId,dir:h.dataset.asnResize,x:e.clientX,y:e.clientY,left:r.left,top:r.top,w:r.width,h:r.height};h.setPointerCapture(e.pointerId);WIN.classList.add('resizing');focus()});h.addEventListener('pointermove',e=>{if(!resize||resize.id!==e.pointerId)return;const c=resize,dx=e.clientX-c.x,dy=e.clientY-c.y;let l=c.left,t=c.top,w=c.w,hg=c.h;if(c.dir.includes('e'))w=Math.max(720,c.w+dx);if(c.dir.includes('s'))hg=Math.max(500,c.h+dy);if(c.dir.includes('w')){w=Math.max(720,c.w-dx);l=c.left+(c.w-w)}if(c.dir.includes('n')){hg=Math.max(500,c.h-dy);t=c.top+(c.h-hg)}w=Math.min(w,innerWidth-l);hg=Math.min(hg,innerHeight-t);Object.assign(WIN.style,{left:l+'px',top:t+'px',width:w+'px',height:hg+'px',transform:'none'});responsive()});const end=e=>{if(!resize||resize.id!==e.pointerId)return;resize=null;WIN.classList.remove('resizing');saveWindow()};h.addEventListener('pointerup',end);h.addEventListener('pointercancel',end)})}
function bindSplitter(){const sp=$('#asnSplitter');if(!sp)return;let d=null;sp.onpointerdown=e=>{if(innerWidth<=760)return;e.preventDefault();d={id:e.pointerId,x:e.clientX,w:st.sidebar};sp.setPointerCapture(e.pointerId)};sp.onpointermove=e=>{if(!d||d.id!==e.pointerId)return;st.sidebar=clamp(d.w+e.clientX-d.x,220,420);WIN.style.setProperty('--asn-sidebar',st.sidebar+'px')};sp.onpointerup=e=>{if(!d||d.id!==e.pointerId)return;d=null;persist(true)};sp.onpointercancel=sp.onpointerup}
function bind(){const mainBtn=$('#openAllSongBtn');if(mainBtn){mainBtn.title='Open AllSong';mainBtn.onclick=open}try{bindFloatingControl(launcher,'allSongNextLauncherPos',open,{left:372,bottom:22})}catch{launcher.addEventListener('click',open)};$('#asnClose').onclick=close;$('#asnMin').onclick=close;$('#asnZoom').onclick=toggleZoom;$('#asnSearch').oninput=e=>{st.query=e.target.value;render()};$$('.asn-nav-item',WIN).forEach(b=>b.onclick=()=>{st.view=b.dataset.view;WIN.classList.add('show-library');persist();render()});$('#asnSidebarList').onclick=e=>{const b=e.target.closest('[data-song]');if(b){select(b.dataset.song);WIN.classList.remove('show-library')}};$('#asnCards').onclick=e=>{const f=e.target.closest('[data-fav]');if(f){e.stopPropagation();toggleFav(f.dataset.fav);return}const q=e.target.closest('[data-queue]');if(q){e.stopPropagation();toggleQueue(q.dataset.queue);return}const c=e.target.closest('[data-song]');if(c)select(c.dataset.song)};$('#asnFavoriteBtn').onclick=()=>st.selected&&toggleFav(st.selected);$('#asnCopyBtn').onclick=async()=>{const s=st.byId.get(st.selected);if(!s)return;await navigator.clipboard?.writeText(`${s.title}\n\n${s.lyrics}`);toast('Copied')};$('#asnPowerSlideBtn').onclick=()=>sendToPowerSlide();$('#asnSendBtn').onclick=()=>sendToPowerSlide();$('#asnQueueBtn').onclick=()=>{if(st.queue.size)sendToPowerSlide([...st.queue]);else if(st.selected)toggleQueue(st.selected)};$('#asnClearQueue').onclick=()=>{st.queue.clear();render()};$('#asnSidebarToggle').onclick=()=>{if(innerWidth<=760){WIN.classList.toggle('mobile-sidebar');return}st.sidebarOpen=!st.sidebarOpen;WIN.classList.toggle('sidebar-hidden',!st.sidebarOpen);persist(true)};$('#asnLibraryToggle').onclick=()=>WIN.classList.toggle('show-library');$('#asnAccount').onclick=()=>{try{window.TahoeAdmin?.restore?.();openPage('account');focusTahoeWindow?.($('#window'))}catch{}};bindMotion();bindSplitter();new ResizeObserver(responsive).observe(WIN);WIN.addEventListener('pointerdown',focus,{capture:true});window.addEventListener('tahoe-state-saved',updateProfile);window.addEventListener('resize',responsive)}
try{const oldAll=allTahoeWindows;allTahoeWindows=function(){const rows=oldAll();if(!rows.includes(WIN))rows.push(WIN);return rows}}catch{}
window.TahoeAdmin?.on?.('profile',()=>{updateProfile();updateAccess()});
if(window.TahoeAdmin?.setCurrentAccess){const f=window.TahoeAdmin.setCurrentAccess.bind(window.TahoeAdmin);window.TahoeAdmin.setCurrentAccess=a=>{const r=f(a);queueMicrotask(updateAccess);return r}}
window.TahoeAllSong={open,close,applyCloudState,getSong:id=>st.byId.get(id)||null,songs:async()=>{await load();return st.songs},search:async q=>{await load();const n=normalize(q);return st.songs.filter(s=>[s.title,...(s.aliases||[])].some(a=>normalize(a).includes(n))).slice(0,30)}};
bind();updateProfile();updateAccess();
})();
